### ISSUE TITLE
ADPassMon is not displaying in menu bar on AD Account

### ISSUE THREAD

**Issue by joelperkins** [macmule/ADPassMon#22]
##### Issue:

ADPassMon v2.20.8 is not displaying in the menu bar on an AD account. There is no evident way to interact with ADPassMon via the GUI. 
##### Attempted Resolution:

Ran `defaults write org.pmbuko.ADPassMon runIfLocal -bool false` as suggested with no change in app behavior. 
Issue persists through `killall cfprefsd`, logout, and reboot. ADPassMon process is running. 
##### Environment:

AD Bound Mac
AD Account w/ local admin right
OS X 10.11 (15A284)

**Comment by pmbuko** [comment]
Thanks for the details. I'm pulling 2.20.8 until I figure out what I messed up.

**Comment by pmbuko** [comment]
Fixed in 2.20.9

**Comment by onderweg** [comment]
I'm having this exact same problem in version 2.20.20 and 2.20.19.
