### ISSUE TITLE
Time?

### ISSUE THREAD

**Issue by jardhug** [macmule/ADPassMon#25]
was asked by macmule to log this. I was having issues with ADPassMon not reporting the correct password expiry date even though i reset my password from AD. Turns out we were missing a reverse DNS entry for our time server and our macs were pointing their time server to it's IP address, because of this the DC wasn't contactable. Changing the time server to it's hostname fixed this issue. This also resolved issues with other user's and having to recreate tickets constantly.

**Comment by macmule** [comment]
Cannot recreate. Hoping that other fixes will mean that this issue will not happen again.
