### ISSUE TITLE
Easier to deploy

### ISSUE THREAD

**Issue by ScarabMonkey** [macmule/ADPassMon#26]
Hi guys

It would be great if there was a way to make this software easier to deploy with reasonable settings.
I have now written an 'outset' script which runs at login to set the defaults that are sensible for our environment, but this still requires the users to open the software and set it to run in startup.

Is there any simple way to also get this to open at startup? Perhaps I just need to add another line to my outset script - but perhaps you guys have a simpler way than using outset at all?

Thanks!

**Comment by macmule** [comment]
Hi,

There are plans afoot for a admin app that would assist in the packaging, including launch agents & generation of a profile.

However, as with all FOSS, time is a factor.

I'll leave this open & will update.

I use a LaunchAgent to run at login for example.

**Comment by ScarabMonkey** [comment]
Brilliant, sounds great! 
I'll have a play with LaunchControl in the meantime :)

**Comment by pboushy** [comment]
@macmule Just to simplify mass deployment/updates, have you considered signing the app and creating a signed pkg?
Creating a pkg would probably be a good initial step to simplifying.

**Comment by macmule** [comment]
Signing the app makes it harder to maintain as the builds need to be signed.

People can compile & sign themselves of course.

I don't think the app installation is much of an issue. More launching it & setting settings.

**Comment by matt-cahill** [comment]
Might be worth updating the docs to indicate that default prefs can be set at a system level (i.e. /Library/Preferences/org.pmbuko.ADPassMon.plist) rather than at the user level. No need to run a script at login to seed preferences.

Unless this isn't recommended by you of course?

**Comment by pmbuko** [comment]
We could mention it in the docs, but this is how preferences that respect Apple's domain structure have always worked. The defaults system works hierarchically, so you can set options for all users in /Library/Preferences and (if necessary) per user options in each ~/Library/Preferences directory. Do you want to submit a pull request with that change? :smiley:

**Comment by matt-cahill** [comment]
Yeah ok, I'll fork and submit something for consideration. Would an example post install script (for Munki or similar) answer the OPs issue?

**Comment by pmbuko** [comment]
That's a good idea. We could add a deployment scripts area for it.

**Comment by pboushy** [comment]
@macmule If you have the LaunchDaemon, LaunchAgent, and an example plist, I can create a shell script that will create a custom pkg for it including clean install vs upgrade that could be used temporarily until there's time for an admin app.

**Comment by macmule** [comment]
This is our current LaunchAgent:

```
 <?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
 <plist version="1.0">
 <dict>
    <key>Label</key>
    <string>com.company.adpassmon</string>
    <key>LimitLoadToSessionType</key>
    <string>Aqua</string>
    <key>Program</key>
    <string>/Applications/ADPassMon.app/Contents/MacOS/ADPassMon</string>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

So you'll need to change the path for the apps location.

**Comment by macmule** [comment]
I'm going to re-open this, as with my new job I'll have to get a new developer cert for macmule so will revisit it then.

**Comment by macmule** [comment]
I'll add something to the wiki, think that will be a decent middle ground for this.

**Comment by macmule** [comment]
@ScarabMonkey, @prbsparx, @matt-cahill, Does this help? https://github.com/macmule/ADPassMon/wiki/Deployment#deploying-adpassmon
