### ISSUE TITLE
ADPM showed days until expiry as a negative number

### ISSUE THREAD

**Issue by steven-j-klein** [macmule/ADPassMon#27]
Today when I unlocked my Mac, I looked in my menu bar and was surprised to see that my password would expire in **[-58d]**.  That's actually when I last changed my password — 58 days ago.

I selected _Re-check Expiration_ and it changed to **[31d]** which is the correct number.

**Comment by macmule** [comment]
Hi Steven,

I think this is related to something I'm to add :)

I'll try & resolve over the week.

**Comment by steven-j-klein** [comment]
BTW, is it my imagination, or did the days used to be reported in brackets? Like this: [31d]

Because I just noticed that it's appearing without brackets in my menubar: 31d

(FWIW, I prefer no brackets.)

**Comment by pmbuko** [comment]
This is true. We did away with the brackets in one of the most recent releases.

**Comment by macmule** [comment]
I'm guessing this is the same issue I have seen. 

ADPM was not re-checking expiration post launch if on launch the domain was not reachable.

Changed the startmeup, passexpires & moved domaintest to intervaldomaintest with the login from the startmeup function being moved to those last 2 functions.

End result? ADPM should now check for password on an interval & will update expiration etc when back on the domain.

This is in the pre-release (https://github.com/macmule/ADPassMon/releases/tag/122), awaiting review before merging.

**Comment by macmule** [comment]
Example log post changes:

23/11/2015 23:14:21.746 ADPassMon[60865]: Domain not reachable.
23/11/2015 23:19:21.958 ADPassMon[60865]: Domain reachable.
23/11/2015 23:19:21.959 ADPassMon[60865]: Testing if password can expire…
23/11/2015 23:19:22.369 ADPassMon[60865]:   Password does expire.
23/11/2015 23:19:22.472 ADPassMon[60865]: Domain reachable.
23/11/2015 23:19:22.472 ADPassMon[60865]: Starting manual process…
23/11/2015 23:19:22.472 ADPassMon[60865]:   Found expireDateUnix in plist: 1.449391035E+9
23/11/2015 23:19:22.570 ADPassMon[60865]:   Got expireDateUnix: 1449391035
23/11/2015 23:19:22.570 ADPassMon[60865]:   Using alt method
23/11/2015 23:19:22.662 ADPassMon[60865]:   New pwdSetDate (16745.36)
23/11/2015 23:19:22.662 ADPassMon[60865]:   ≥ plist value (1.674536E+4) so we use it
23/11/2015 23:19:22.672 ADPassMon[60865]:   daysUntilExp: 12.38822
23/11/2015 23:19:22.673 ADPassMon[60865]:   expirationDate: Sunday, 6 December 2015 08:38:24
23/11/2015 23:19:22.674 ADPassMon[60865]: ADPassMon password method selected
23/11/2015 23:19:22.674 ADPassMon[60865]: Testing Keychain Lock state...
23/11/2015 23:19:22.695 ADPassMon[60865]:   Keychain unlocked...
