### ISSUE TITLE
The *About* box links to pmbuko's website

### ISSUE THREAD

**Issue by steven-j-klein** [macmule/ADPassMon#28]
As a (relatively) new user, I wanted to find the documentation. I looked in _About ADPassMon…_ and saw this:
**Documentation:**
    [http://yourmacguy.wordpress.com](http://yourmacguy.wordpress.com/ADPassMon/)

I clicked the link and it took me here: http://yourmacguy.wordpress.com/ADPassMon/

On that page I found a link to this page: https://github.com/macmule/ADPassMon/wiki

Shouldn't the link in the about box go to the [documentation page on GitHub](https://github.com/macmule/ADPassMon/wiki)?

**Comment by macmule** [comment]
Will update next release!

**Comment by macmule** [comment]
Thanks! Added to 2.20.11 pre-release, will check off some other things & once reviewed release.
