### ISSUE TITLE
pwPolicyButton

### ISSUE THREAD

**Issue by ddcdennisb** [macmule/ADPassMon#29]
when using defaults write to set a pwPolicyButton its still just has the default "OK"

It was recommended trying pwPolicyButtonTitle as well and that didn't work.

**Comment by pmbuko** [comment]
Just making sure. Are you restarting ADPassMon after making these prefs changes?

**Comment by ddcdennisb** [comment]
I have.

**Comment by macmule** [comment]
hmm.. i've been having a poke around, shouldn't the key be: pwPolicyURLButtonTitle

Where did you see pwPolicyButtonTitle?

**Comment by ddcdennisb** [comment]
https://yourmacguy.wordpress.com/adpassmon/https://yourmacguy.wordpress.com/adpassmon/  under the section
 called password policy reminder

~DB

**Comment by macmule** [comment]
Ah.. https://github.com/macmule/ADPassMon/wiki/Customization#password-policy-reminder there too.. ok.. i might have stomped all over it when merging

**Comment by macmule** [comment]
Can you please try: https://github.com/macmule/ADPassMon/releases/tag/122

It's a pre-release build, but think I've added it back in.

**Comment by ddcdennisb** [comment]
When I click on Change Password I get no popup windows.

~DB

Dennis Browning
Lead Apple Information Systems Architect

1 Howard St
Burlington, VT 05401
dealertrack.com

p
802.540.7447

f
802.540.7447

m
802.734.5248

dealertrack technologies®

Confidentiality Notice: This e-mail and any attachments may contain confidential, proprietary information of Dealertrack Technologies. It is intended solely for the named recipient(s) listed above and
 should be maintained in strictest confidence. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of the information contained herein (including any reliance thereon) is STRICTLY PROHIBITED. If
 you have received this e-mail in error, please immediately notify the sender and delete this information from your computer and destroy any related paper copies. Unless otherwise expressly stated in the text of the e-mail, the addition of a typed name or initials
 to this e-mail does not (i) evidence an intent to sign the e-mail or (ii) constitute either (a) a signature or (b) consent to use electronic records or signatures in place of a writing or a handwritten signature.

**Comment by macmule** [comment]
Suboptimal. 

Ok, lemme have another nose tomorrow. 

Regards,

Ben.

**Comment by macmule** [comment]
Oh. 

Can you supply a copy of the ADPassMon plist?

Regards,

Ben.

**Comment by ddcdennisb** [comment]
See attached.

~DB

Dennis Browning
Lead Apple Information Systems Architect

1 Howard St
Burlington, VT 05401
dealertrack.com

p
802.540.7447

f
802.540.7447

m
802.734.5248

dealertrack technologies®

Confidentiality Notice: This e-mail and any attachments may contain confidential, proprietary information of Dealertrack Technologies. It is intended solely for the named recipient(s) listed above and
 should be maintained in strictest confidence. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of the information contained herein (including any reliance thereon) is STRICTLY PROHIBITED. If
 you have received this e-mail in error, please immediately notify the sender and delete this information from your computer and destroy any related paper copies. Unless otherwise expressly stated in the text of the e-mail, the addition of a typed name or initials
 to this e-mail does not (i) evidence an intent to sign the e-mail or (ii) constitute either (a) a signature or (b) consent to use electronic records or signatures in place of a writing or a handwritten signature.

**Comment by macmule** [comment]
Sorry the attachment didn't come through. Can you post it on the issue on Github?

**Comment by macmule** [comment]
nvm.. Can you please test: https://github.com/macmule/ADPassMon/releases/tag/123

**Comment by ddcdennisb** [comment]
Success!!

~DB

Dennis Browning
Lead Apple Information Systems Architect

1 Howard St
Burlington, VT 05401
dealertrack.com

p
802.540.7447

f
802.540.7447

m
802.734.5248

dealertrack technologies®

Confidentiality Notice: This e-mail and any attachments may contain confidential, proprietary information of Dealertrack Technologies. It is intended solely for the named recipient(s) listed above and
 should be maintained in strictest confidence. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of the information contained herein (including any reliance thereon) is STRICTLY PROHIBITED. If
 you have received this e-mail in error, please immediately notify the sender and delete this information from your computer and destroy any related paper copies. Unless otherwise expressly stated in the text of the e-mail, the addition of a typed name or initials
 to this e-mail does not (i) evidence an intent to sign the e-mail or (ii) constitute either (a) a signature or (b) consent to use electronic records or signatures in place of a writing or a handwritten signature.

**Comment by macmule** [comment]
Awesome.. i'll merge & release 2.20.11 shortly

**Comment by ddcdennisb** [comment]
Awesome.  Thanks

~DB

Dennis Browning
Lead Apple Information Systems Architect

1 Howard St
Burlington, VT 05401
dealertrack.com

p
802.540.7447

f
802.540.7447

m
802.734.5248
