### ISSUE TITLE
'Change Password' greyed out on first run with deployed plist

### ISSUE THREAD

**Issue by mattretzer** [macmule/ADPassMon#33]
Hello guys, trying this out for our environment.
So far looks good, except when deploying a custom plist (via defaults) for users prior to running the App, on first run the 'Change Password' is greyed out.  
The rest of the settings are deploying fine, and if we either relaunch the App, 'Re-check Expiration' or 'Test Settings' then the option becomes available. But I'd rather it be ready to go right away?
I tested on a few Macs, this seems a consistent issue in our environment with these settings.
I think there were settings that I tested where this was not the case (maybe it's the manual expiration check?)

Items I am deploying:
defaults write $plistPath accTest 0
defaults write $plistPath enableKeychainLockCheck 1
defaults write $plistPath enableNotifications 1
defaults write $plistPath expireAge "60"
defaults write $plistPath pwPolicy "Passwords must have at least 8 characters etc"
defaults write $plistPath selectedBehaviour 2
defaults write $plistPath selectedMethod 1
defaults write $plistPath warningDays 7

**Comment by macmule** [comment]
which version?

**Comment by mattretzer** [comment]
2.20.10

**Comment by macmule** [comment]
Hey @mattretzer, @pmbuko is pushing 2.20.12 later.. can you try after that?

**Comment by mattretzer** [comment]
Yes, no problem.  Thanks for the quick response.
Will update this issue with my results:)

**Comment by pmbuko** [comment]
2.20.12 is out now.

**Comment by mattretzer** [comment]
Hi @pmbuko & @macmule,
Unfortunately I am still seeing the same thing with 2.20.12- greyed out ChangePassword option on first run.

**Comment by pmbuko** [comment]
How are you deploying the defaults values? Also, could you please copy/paste what the Console log shows (filter or ADPassMon) after a first launch?

**Comment by mattretzer** [comment]
I am deploying those values via defaults write commands (basically
what you see above):
Creating a plist file via defaults write(s) to /tmp, copying the
/tmp/.plist to all user accounts (& user template) and correcting
permissions for the copied .plists.
Am I missing a value?

Here's what the log says:

11/30/15 2:06:04.230 PM ADPassMon[27689]: Running on OS 10.10.x
11/30/15 2:06:04.257 PM ADPassMon[27689]: Running under a network account.
11/30/15 2:06:04.265 PM ADPassMon[27689]: ADPassMon password method selected
11/30/15 2:06:04.517 PM ADPassMon[27689]: Domain reachable.
11/30/15 2:06:04.517 PM ADPassMon[27689]: Testing if password can expire…
11/30/15 2:06:04.544 PM ADPassMon[27689]:   Password does expire.
11/30/15 2:06:04.564 PM ADPassMon[27689]: Domain reachable.
11/30/15 2:06:04.564 PM ADPassMon[27689]: Starting manual process…
11/30/15 2:06:04.565 PM ADPassMon[27689]:   Found expireDateUnix in plist: 0
11/30/15 2:06:04.619 PM ADPassMon[27689]:   Got expireDateUnix: 1453476466
11/30/15 2:06:04.619 PM ADPassMon[27689]:   Using alt method
11/30/15 2:06:04.646 PM ADPassMon[27689]:   New pwdSetDate (16762.64)
11/30/15 2:06:04.647 PM ADPassMon[27689]:   will be saved to plist.
11/30/15 2:06:04.656 PM ADPassMon[27689]:   daysUntilExp: 52.84412
11/30/15 2:06:04.658 PM ADPassMon[27689]:   expirationDate: Friday,
January 22, 2016 at 10:21:36 AM
11/30/15 2:06:04.660 PM ADPassMon[27689]: ADPassMon password method selected
11/30/15 2:06:04.661 PM ADPassMon[27689]: Testing Keychain Lock state...
11/30/15 2:06:04.683 PM ADPassMon[27689]:   Keychain unlocked...

**Comment by pmbuko** [comment]
Everything looks good to me. The Change Password menu item should only be greyed out when ADPassMon can't detect the domain. The log clearly shows "Domain reachable", though. Are these log entries from a launch that resulted in a greyed out menu item?

**Comment by mattretzer** [comment]
yes, they are fro a launch with a greyed out 'Change password' & 'Refresh
Kerberos'; tested on 10.10 & 10.11, same results.

And once I 'Re-check Expiration' it comes in fine, subsequent launches are
fine too.

I think when I was trying different plist settings I had some where this
was not the case. I'll play with it a little more to see if I can help pin
it down.

**Comment by pmbuko** [comment]
One more thing to check. Before launching for the first time, but after applying defaults, as the user, run `defaults read org.pmbuko.ADPassMon`. Save the output, then launch ADPassMon and do Re-check Expirtation. Run the `defaults read` command again and compare the output.

**Comment by macmule** [comment]
@mattretzer have you tried setting things via a profile? Also, I guess ADPassMon is being launched whilst these changes are being made?

**Comment by macmule** [comment]
@mattretzer any updates?

**Comment by macmule** [comment]
@mattretzer the writing out plist & copying will not work with CFPrefsd, so either a profile or a defaults read on the plist afterwards (as @pmbuko) mentions should resolve.

I'm putting this down as "wontfix" for now, as it's more of an OS/deployment issue, please can you advise if anything we've mentioned has worked?

We'll then close the issue off, or I'll close it sometime in March.

**Comment by bryanzak** [comment]
I'm seeing the exact same issue on a completely fresh install. As a test, the app is not running, there are no existing prefs in the current user Library and I run this script

#!/bin/bash

adpassmonprefs="/Library/Preferences/org.pmbuko.ADPassMon"

defaults write "${adpassmonprefs}" "expireAge" -int 180
defaults write "${adpassmonprefs}" "isBehaviour2Enabled" -int 1
defaults write "${adpassmonprefs}" "selectedBehaviour" -int 2
defaults write "${adpassmonprefs}" "selectedMethod" -int 1
defaults write "${adpassmonprefs}" "warningDays" -int 7

If I then open the app, the Change Password menu item is grayed out until I do a Refresh

This is using 2.20.20

**Comment by macmule** [comment]
I'll see if i can replicate this, & try to fix in 2.21.0

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/154

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/155

**Comment by macmule** [comment]
Closing off as sorted in 2.21.0
