### ISSUE TITLE
Issue with Disabling Password Changes

### ISSUE THREAD

**Issue by dire-alpaca** [macmule/ADPassMon#35]
Hi there,

I was testing ADPassMon and noticed something odd.

When setting this plist item (allowPasswordChange):
<code>defaults write org.pmbuko.ADPassMon allowPasswordChange -bool false</code>

Which should:

> You may not wish the user to change their password via ADPassMon at all (for example, if your users are required to use a website). You can set this with the following command or via MCX. Any password policy options you've set will still appear, but when the user clicks “OK” the dialog box is dismissed & no further action is taken. This option is available in the preferences window.

I found that I can still click and select Change Password from the menu and ADPassMon will show me the password policy and then (depending on setting) will either bring up system preferences or prompt for a password change through ADPassMon.

I also noticed that the Password policy would not display the button to goto the website url specified.

I am testing on 10.10.5 as well. Other than that, everything else works quite well.

Here is the output of the plist/settings:

<code>
mac-mbp09-02:~ mtustin$ defaults read org.pmbuko.ADPassMon
{
    accTest = 0;
    allowPasswordChange = false;
    changePasswordPromptWindowText = "Please visit the account portal to change/reset your password.";
    enableKerbMinder = 1;
    enableKeychainLockCheck = 1;
    expireDateUnix = 1464477079;
    "first_run" = 0;
    isBehaviour2Enabled = 0;
    "menu_title" = 179d;
    prefsLocked = false;
    pwPolicy = "At SMS, Staff are required to have a password that is at least 8 characters long. Students are required at least 4 characters. Please visit the Account Portal to change/reset your password.";
    pwPolicyURLBrowser = "Google Chrome";
    pwPolicyURLButton = "Visit Account Portal";
    pwPolicyURLButtonURL = "https://accounts.stmarg.ca";
    selectedBehaviour = 1;
    tooltip = "Your password expires\nSat May 28 16:11:19 PDT 2016";
}
</code>

**Comment by pmbuko** [comment]
Thanks for letting us know. Are you using release 2.20.12?

**Comment by dire-alpaca** [comment]
Yes, I was testing using 2.20.12.

Thanks!

**Comment by macmule** [comment]
@an-alpaca Thanks.. I'll have a look at this this week

**Comment by matt-cahill** [comment]
I'm also seeing the same behaviour on 10.11.3 using 2.20.14 (130)

**Comment by matt-cahill** [comment]
Setting pwPolicyURLButtonTitle to a value using defaults write restores the functionality. Possibly this issue is similar #45

**Comment by pmbuko** [comment]
That's good to know. I think we just need to make the disable part more robust.

**Comment by matt-cahill** [comment]
Seems to be two seperate but intertwined issues.

Firstly I can't find `pwPolicyURLButton` in the code, I think this is just a typo in the docs. Should be `pwPolicyURLButtonTitle`

Secondly if either `pwPolicyURLButtonTitle` or `pwPolicyURLButtonURL` are not set then `pwPolicyUpdateExternal` never gets set in the block starting at [line 1235](https://github.com/macmule/ADPassMon/blob/master/ADPassMon/ADPassMonAppDelegate.applescript#L1235) and thus the password update window is displayed at [line 940](https://github.com/macmule/ADPassMon/blob/master/ADPassMon/ADPassMonAppDelegate.applescript#L940) even if `allowPasswordChange` is set to false.

**Comment by matt-cahill** [comment]
I updated the wiki regarding the defaults write for `pwPolicyURLButtonTitle`

**Comment by dire-alpaca** [comment]
![screen shot 2016-01-26 at 9 58 26 am](https://cloud.githubusercontent.com/assets/12103047/12589640/98b5988c-c413-11e5-9216-a295c5f5982e.png)

Just did some further testing and found the prompts seem to work properly now with the different config option `pwPolicyURLButtonTitle`. Thanks @matt-cahill for the code digging!

Settings set:

```
    pwPolicy = "At SMS, Staff are required to have a password that is at least 8 characters long. Students are required at least 4 characters. Please visit the Account Portal to change/reset your password.";
    pwPolicyButton = Okay;
    pwPolicyURLBrowser = "Google Chrome";
    pwPolicyURLButtonTitle = "SMS Account Portal";
    pwPolicyURLButtonURL = "https://accounts.stmarg.ca";
    selectedBehaviour = 2;
```

I do believe further robustness is require on some of the settings. As @matt-cahill said above, you have to set many options in order to stop the dialogs from coming up.

**Comment by macmule** [comment]
Merged, will be in next release.
