### ISSUE TITLE
Keychain First Aid disappearing in future versions of OS X

### ISSUE THREAD

**Issue by pboushy** [macmule/ADPassMon#36]
I've been told by some sources that Keychain Access's Keychain First Aid functionality is disappearing in future versions of OS X. Potentially as early as 10.11.2 since it's broken in 10.11.1...

Will this have an impact on ADPassMon's ability to fix the keychain password?

**Comment by pmbuko** [comment]
This should not affect us since ADPassMon doesn't use it.

**Comment by macmule** [comment]
Agreed with @pmbuko.

Closing off, but @prbsparx thanks for the warning.
