### ISSUE TITLE
Remaining days until Password change turning negative

### ISSUE THREAD

**Issue by w4774** [macmule/ADPassMon#37]
Hey,
I've been using your helpfull tool for some time now, but it seems to have a little problem.
About 50% of the time, the remaining days until I need to change my password are displayed in the negative, bot in the status bar and the adpassmon notifications.
I mean, it's still kinda correct....
It displays the remaining time as "-163 days", our passworld policy requires the password to be changed every 180 days, which means I have 17 days left, which is correct.

Is there some way to fix this? If I can provide you with any more information, I'll be happy to help.

I am using release 2.20.12 (127) on OS X 10.10.5.

**Comment by pmbuko** [comment]
Next time you see this happen, can you open Console.app, add "adpassmon" to the search filter and copy/paste the last group of log entries here? Feel free to redact any IP addresses or domain names.

**Comment by w4774** [comment]
it happened again this morning, here is a screen of the log:
http://i.imgur.com/6MWhrib.png

If I click "Re-Check expiration", sometimes it pulls the correct date and the expiration days got changed to "15d", see the log for that:
http://i.imgur.com/Zc6EYdc.png

**Comment by jardhug** [comment]
i had a similar problem, unbinding and rebinding the mac fixed it for me.

**Comment by pmbuko** [comment]
Thanks for this. I see that when it works properly, it is using the "msDS method" to get the password age. When it doesn't work it is using the "alt method". 

I would try unbinding and rebinding as suggested. You could be experiencing an intermittent domain problem, or one of your domain servers may be configured slightly differently than the others.

-- Peter (from phone)

**Comment by pmbuko** [comment]
Here are some more details on how ADPassMon chooses which method (msDS or alt) to use. It first tries this command:

`dscl localhost read /Search/Users/$USER & " msDS-UserPasswordExpiryTimeComputed`

If that comes back with a match, then the 'msDS' method is used. This is the faster, more accurate method. If the command comes back with no match, then the 'alt' method is used.

This is why I suspect either an intermittent issue with your domain or that one server in the pool is not configured properly.

**Comment by steven-j-klein** [comment]
For me, this problem is very infrequent, but I did see it just now: -87d.

Possibly relevant: I woke my MacBook Pro _before_ plugging in the Ethernet cable.

Using the **Refresh Kerberos Ticket** fixed it for me.  (Apparently this AM my ticket had expired, because when I selected Refresh I saw this: "No Kerberos ticket for Active Directory was found. Do you want to renew it?")

Log entries below:

> 12/18/15 7:01:57.177 AM WindowServer[158]: CGError post_notification(const CGSNotificationType, void *const, const size_t, const bool, const CGSRealTimeDelta, const int, const CGSConnectionID *const, const pid_t): Timed out 0.250 second wait for reply from "ADPassMon" for synchronous notification type 109 (<unknown>) (CID 0x27303, PID 551)
> 12/18/15 7:02:11.828 AM ADPassMon[551]: Starting auto process…
> 12/18/15 7:02:11.829 AM ADPassMon[551]:   Found expireDateUnix in plist: 1450644455
> 12/18/15 7:02:11.989 AM ADPassMon[551]:   Using alt method
> 12/18/15 7:02:12.067 AM ADPassMon[551]:   New pwdSetDate (16699.87)
> 12/18/15 7:02:12.071 AM ADPassMon[551]:   ≥ plist value (1.669987E+4) so we use it
> 12/18/15 7:02:12.082 AM ADPassMon[551]:   daysUntilExp: -87.63153
> 12/18/15 7:02:12.094 AM ADPassMon[551]:   expirationDate: Monday, September 21, 2015 at 3:52:48 PM
> 12/18/15 7:02:12.148 AM ADPassMon[551]: Triggering notification…
> 12/18/15 7:02:12.149 AM ADPassMon[551]: ADPassMon password method selected
> 12/18/15 7:02:12.150 AM ADPassMon[551]: Testing Keychain Lock state...
> 12/18/15 7:02:12.182 AM ADPassMon[551]:   Keychain unlocked...
> 12/18/15 7:08:26.707 AM ADPassMon[551]: Testing for Kerberos ticket…
> 12/18/15 7:08:26.823 AM ADPassMon[551]:   No ticket found
> 12/18/15 7:10:00.779 AM ADPassMon[551]:   Ticket acquired
> 12/18/15 7:10:02.843 AM ADPassMon[551]: Testing for Kerberos ticket…
> 12/18/15 7:10:02.886 AM ADPassMon[551]:   Ticket found and renewed
> 12/18/15 7:10:02.945 AM ADPassMon[551]: Starting auto process…
> 12/18/15 7:10:02.946 AM ADPassMon[551]:   Found expireDateUnix in plist: 1.450644455E+9
> 12/18/15 7:10:03.252 AM ADPassMon[551]:   Got expireDateUnix: 1450644455
> 12/18/15 7:10:03.252 AM ADPassMon[551]:   Using msDS method
> 12/18/15 7:10:03.266 AM ADPassMon[551]:     daysUntilExp: 2.359398148148
> 12/18/15 7:10:03.294 AM ADPassMon[551]: Triggering notification…
> 12/18/15 7:10:03.296 AM ADPassMon[551]: ADPassMon password method selected
> 12/18/15 7:10:03.296 AM ADPassMon[551]: Testing Keychain Lock state...
> 12/18/15 7:10:03.326 AM ADPassMon[551]:   Keychain unlocked...

**Comment by macmule** [comment]
I think this is related to: https://github.com/macmule/ADPassMon/issues/43

@w4774 anything new to report?

**Comment by macmule** [comment]
@w4774 Please test the latest release: https://github.com/macmule/ADPassMon/releases/tag/2.20.18

I've changed it so ADPassMon updates the plist when it calculates expiry via ldapsearch too (previously it was just msDS). 

When "offline" ADPassMon reads the value from the plist.. So i think what was happening was that ADPassMon was not updating the plist, & when waking from sleep it was seeing the mac as being "offline" & show displaying the wrong expiration date.

**Comment by macmule** [comment]
Can you try? https://github.com/macmule/ADPassMon/releases/tag/2.20.20

**Comment by smashism** [comment]
Hi @macmule, I know we've had a similar conversation elsewhere, but in our environment the date is always negative.

results of `defaults read ~/Library/Preferences/org.pmbuko.ADPassMon.plist`:

`accTest = 0;
enableKeychainLockCheck = 1;
expireDateUnix = 1462826303;
"first_run" = 0;
isBehaviour2Enabled = 0;
"menu_title" = "-37d";
pwdSetDate = "16930.86";
selectedBehaviour = 1;
tooltip = "Your password expires\\nMonday, May 9, 2016 at 3:38:24 PM";`

Is there a way to have it flip the information to show a countdown rather than a elapsed days?

**Comment by macmule** [comment]
@smashism can you post some logs?

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/154

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/155

**Comment by macmule** [comment]
Please Test: https://github.com/macmule/ADPassMon/releases/tag/163 

@w4774, @danprk, @steven-j-klein, @smashism

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
