### ISSUE TITLE
Password date should be less than 365 on [Auto] and when setting [Manual] = 90 receiving -40

### ISSUE THREAD

**Issue by sp4rker** [macmule/ADPassMon#38]
Reset and performed action auto and then manual 90
12/11/15 11:19:15.008 AM ADPassMon[1971]: **\* -[ADPassMonAppDelegate revertDefaults:]: 2015-12-11 11:19:15.006 defaults[2629:47744] 
Domain (org.pmbuko.ADPassMon) not found.
Defaults have not been changed. (error 1)
12/11/15 11:25:47.674 AM ADPassMon[1971]: selectedMethod: 90
12/11/15 11:25:47.724 AM ADPassMon[1971]: Domain reachable.
12/11/15 11:25:47.724 AM ADPassMon[1971]: Starting manual process…
12/11/15 11:25:47.726 AM ADPassMon[1971]:   Found expireDateUnix in plist: 910692730085
12/11/15 11:25:47.783 AM ADPassMon[1971]:   Got expireDateUnix: 910692730085
12/11/15 11:25:47.783 AM ADPassMon[1971]:   Using alt method
12/11/15 11:25:47.809 AM ADPassMon[1971]:   New pwdSetDate (16650.69)
12/11/15 11:25:47.809 AM ADPassMon[1971]:   will be saved to plist.
12/11/15 11:25:47.815 AM ADPassMon[1971]:   daysUntilExp: -40.11957
12/11/15 11:25:47.816 AM ADPassMon[1971]:   expirationDate: Sunday, November 1, 2015 at 8:33:36 AM
12/11/15 11:25:47.817 AM ADPassMon[1971]: Triggering notification…
12/11/15 11:25:47.817 AM ADPassMon[1971]: Native password method selected
12/11/15 11:25:47.818 AM ADPassMon[1971]: Testing Universal Access settings…
12/11/15 11:25:50.798 AM ADPassMon[1971]:   Prompting for password
12/11/15 11:26:01.805 AM ADPassMon[1971]:   Enabled
12/11/15 11:26:01.806 AM ADPassMon[1971]: Skipping Keychain Lock state check...
12/11/15 11:26:10.572 AM ADPassMon[1971]: selectedMethod: 1
12/11/15 11:26:10.622 AM ADPassMon[1971]: Domain reachable.
12/11/15 11:26:10.622 AM ADPassMon[1971]: Starting auto process…
12/11/15 11:26:10.751 AM ADPassMon[1971]:   Got expireDateUnix: 910692730085
12/11/15 11:26:10.751 AM ADPassMon[1971]:   Using msDS method
12/11/15 11:26:10.761 AM ADPassMon[1971]:     daysUntilExp: 1.052364430689E+7
12/11/15 11:26:10.764 AM ADPassMon[1971]: Native password method selected
12/11/15 11:26:10.764 AM ADPassMon[1971]: Testing Universal Access settings…
12/11/15 11:26:10.764 AM ADPassMon[1971]:   Enabled
12/11/15 11:26:10.765 AM ADPassMon[1971]: Skipping Keychain Lock state check...
12/11/15 11:26:18.581 AM ADPassMon[1971]: selectedMethod: 90
12/11/15 11:26:18.633 AM ADPassMon[1971]: Domain reachable.
12/11/15 11:26:18.633 AM ADPassMon[1971]: Starting manual process…
12/11/15 11:26:18.635 AM ADPassMon[1971]:   Found expireDateUnix in plist: 910692730085
12/11/15 11:26:18.670 AM ADPassMon[1971]:   Got expireDateUnix: 910692730085
12/11/15 11:26:18.670 AM ADPassMon[1971]:   Using alt method
12/11/15 11:26:18.697 AM ADPassMon[1971]:   New pwdSetDate (16650.69)
12/11/15 11:26:18.698 AM ADPassMon[1971]:   ≥ plist value (1.665069E+4) so we use it
12/11/15 11:26:18.704 AM ADPassMon[1971]:   daysUntilExp: -40.11993
12/11/15 11:26:18.704 AM ADPassMon[1971]:   expirationDate: Sunday, November 1, 2015 at 8:33:36 AM
12/11/15 11:26:18.707 AM ADPassMon[1971]: Triggering notification…
12/11/15 11:26:18.708 AM ADPassMon[1971]: Native password method selected
12/11/15 11:26:18.708 AM ADPassMon[1971]: Testing Universal Access settings…
12/11/15 11:26:18.708 AM ADPassMon[1971]:   Enabled
12/11/15 11:26:18.708 AM ADPassMon[1971]: Skipping Keychain Lock state check...

**Comment by pmbuko** [comment]
Just to confirm, are you using the latest release, 2.20.12?

**Comment by sp4rker** [comment]
Yes, just downloaded to day, thanks for responding so quickly

**Comment by pmbuko** [comment]
Can you try running these script and compare their outputs?
https://gist.github.com/pmbuko/0f8c6904def80cbb1265
https://gist.github.com/pmbuko/132bfd7b45c806d84bab

**Comment by sp4rker** [comment]
Username:        xxxxx
Expiration date: Wed Sep 13 18:48:05 PST 30828
Number of days:  10523644

Wed Sep 13 18:48:05 PST 30828

**Comment by sp4rker** [comment]
So anything I can do to make it not think my password update should occur in the past?

12/11/15 11:25:47.815 AM ADPassMon[1971]:   daysUntilExp: -40.11957
12/11/15 11:25:47.816 AM ADPassMon[1971]:   expirationDate: Sunday, November 1, 2015 at 8:33:36 AM

**Comment by macmule** [comment]
@sp4rker Can you post results from the second script that @pmbuko linked?

**Comment by sp4rker** [comment]
Username: xxxxx
Expiration date: Wed Sep 13 18:48:05 PST 30828
Number of days: 10523644

Wed Sep 13 18:48:05 PST 30828

**Comment by pmbuko** [comment]
Hmmm. Something is amiss. The number that the script is getting from AD is probably not in the format it's expecting.

Please try this more verbose script:

https://gist.github.com/pmbuko/433dabd70514fd0bbd52 https://gist.github.com/pmbuko/433dabd70514fd0bbd52

**Comment by sp4rker** [comment]
Commented out domain info:

No such key: userAccountControl
No such key: SMBPasswordLastSet
(standard_in) 1: parse error
(standard_in) 1: parse error
(standard_in) 1: parse error
myDomain:         xxx.xxx
myLDAP:           2sgpitvwdc03.xxx.xxx.
mySearchBase:     DC=xxx,DC=xxx
uAC:
passExpires:      yes
expireAgeDays:    90
pwdSetDateRaw:
pwdSetDateUnix:
pwdSetDate:
todayUnix:        1450306390
today:            16785.95358796296296296296
daysUntilExp:
daysUntilExpNice:

**Comment by sp4rker** [comment]
Any thoughts on this?

**Comment by macmule** [comment]
@sp4rker  can you try? https://gist.github.com/macmule/a6bbd0d567fec5f2b5d2

It's basically the same thing as what @pmbuko passed you, just horribly written in python.

Only difference is that is will get a list of all ldap servers & if it fails to get a value from one, it'll move to the other.

This should return data for the below & not fail. As will try all LDAP servers

No such key: userAccountControl
No such key: SMBPasswordLastSet

**Comment by macmule** [comment]
@sp4rker any update?

**Comment by macmule** [comment]
@sp4rker Please test the latest release (2.20.18).

**Comment by macmule** [comment]
Closing as cannot replicate & no response from OP.
