### ISSUE TITLE
Non-mobile AD accounts are being detected as local

### ISSUE THREAD

**Issue by pmbuko** [macmule/ADPassMon#39]
via Slack channel:

" i can’t get ADpassMon to start up with an AD account. The log claims it is a local account, so adpassmon quits."

I asked him to run `dscl localhost read /Search/Users/$USER AuthenticationAuthority` and see if the output contains "Active Directory".

He has a non-mobile AD accout and the output was `AuthenticationAuthority: ;Kerberosv5;;kyle@ISB.LOCAL;ISB.LOCAL; ;NetLogon;kyle;ISB`

We should consider changing [line 161](https://github.com/macmule/ADPassMon/blob/master/ADPassMon/ADPassMonAppDelegate.applescript#L161) to read:

`if "NetLogon" is in accountLoc`

**Comment by fridomac** [comment]
Same problem here, if you need more logs or info, please contact me (slack or email)

**Comment by pmbuko** [comment]
I'm going to push this update today.

**Comment by pmbuko** [comment]
Please try the 2.20.13 release. https://github.com/macmule/ADPassMon/releases/tag/2.20.13
