### ISSUE TITLE
A minor cosmetic issues with the Change Password function

### ISSUE THREAD

**Issue by steven-j-klein** [macmule/ADPassMon#40]
I just used the change password function for the first time. The Old Password, New Password, and Verify Password fields were empty. I filled them out, and it worked as expected.

Immediately afterwards I tried to use it a second time, and the Old Password, New Password, and Verify Password fields were populated with bullets, when they should have been empty.

(I also noticed that the number of bullets equaled the number of characters in the passwords. This doesn't bother me, but it seems to be common practice in other systems to always show the same number of bullets, regardless of password length.)

**Comment by macmule** [comment]
Ah. I'll amend it to wipe the values so not seen second run. 

The •'s appear via a secure text field, not sure about changing length. But the 1st issue should be easy to fix.

**Comment by macmule** [comment]
Added @avatharian's PR to master branch. Will be in next release.
