### ISSUE TITLE
Not working when at home connected to VPN

### ISSUE THREAD

**Issue by amusser** [macmule/ADPassMon#44]
We are looking to deploy ADPassMon to our users, however we have many who work from home at times and while testing, I've found that it does not work when connected to VPN.

We run a Cisco VPN and use the built-in Mac client to connect.  When connected to VPN the Refresh Ticket and Change Password options are greyed out.  A look at the log shows "Domain not reachable".  Our domain is reachable as logins are permitted for users not cached on the machine.

I ran your script ad_pass_exp.sh and got the following:

ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)
No such key: userAccountControl
ldap_sasl_interactive_bind_s: Can't contact LDAP server (-1)
(standard_in) 1: parse error
No such key: pwdLastSet
myLDAP:           192.168.x.x
mySearchBase:  
uAC:              512
passExpires:      yes
expireAgeUnix:  
expireAge:  
pwdSetDateRaw:    130977844049510960
pwdSetDateUnix:   1453310804.95109600000000000000
pwdSetDate:       16820.72690915620370370370
todayUnix:        1453318462
today:            16820.81553240740740740740
daysUntilExp:     -.08862325120370370370
daysUntilExpNice: -

The value for myLDAP is being set to my home router instead of the DC. 

scutil --dns  shows the first resolver as my home router and then the DCs as the second resolver.

Is there not a way to have this program work on a VPN connection?

**Comment by pmbuko** [comment]
Do you know if your VPN allows split tunnels, or when activated does all network traffic go over the vpn connection?

**Comment by macmule** [comment]
FWIW, I use Cisco's In-Built VPN client too & have been working from home since October 22nd. 

ADPassMon works for me.

**Comment by amusser** [comment]
Our VPN allows split tunneling

**Comment by amusser** [comment]
So is split tunneling an issue?

**Comment by pmbuko** [comment]
Likely yes, but it probably depends on the specifics of your tunnel and routing table.

**Comment by macmule** [comment]
"The value for myLDAP is being set to my home router instead of the DC"

That really strikes me as odd.

**Comment by macmule** [comment]
@amusser Were you running the script when having had a kerberos ticket issued?

**Comment by amusser** [comment]
Yes I am running the script while I have a ticket

**Comment by macmule** [comment]
@amusser can you try? https://gist.github.com/macmule/a6bbd0d567fec5f2b5d2

It's basically the same thing as what @pmbuko passed you, just horribly written in python.

Only difference is that is will get a list of all ldap servers & if it fails to get a value from one, it'll move to the other.

**Comment by amusser** [comment]
Getting the follow error:

Traceback (most recent call last):
  File "./PassMon.py", line 120, in <module>
    for index, item in enumerate(searchBase):
NameError: name 'searchBase' is not defined

**Comment by macmule** [comment]
Right. 

What does the output of: klist --json

Look like?

Regards,

Ben.

**Comment by macmule** [comment]
@amusser I've updated the gist.. can you try it again please? https://gist.github.com/macmule/a6bbd0d567fec5f2b5d2

**Comment by amusser** [comment]
ERROR: No LDAP servers found

**Comment by macmule** [comment]
@amusser One last thing to try (change mycompany.com for your domain):

`dig -t srv _ldap._tcp.mycompany.com +noall +answer`

You should receive:

`;; Truncated, retrying in TCP mode.`
`; <<>> DiG 9.8.3-P1 <<>> -t srv _ldap._tcp.mycompany.com +noall +answer`
`;; global options: +cmd`
`_ldap._tcp.mycompany.com. 600    IN  SRV 0 100 389 dc03.mycompany.com.`
`_ldap._tcp.mycompany.com. 600    IN  SRV 0 100 389 dc02.mycompany.com.`

If not, then then something on the VPN is not allowing the queries.

If you get a reply, can you post a redacted version of it?

**Comment by amusser** [comment]
It's not returning anything.  Could this have anything to do with cached credentials?

**Comment by macmule** [comment]
Nope. 

That's more of a network lookup & is completely separate from credentials. 

What's happening is that ADPassMon is realising it cannot connect to your domain & as is acting accordingly.

So ADPassMon is working correctly for how your VPN is setup. 

As mentioned, similar VPN & the dig command returns LDAP servers for me.

**Comment by amusser** [comment]
OK.  I'll research this further from my end.  Thanks for all your help.

**Comment by macmule** [comment]
No problem. 

I don't think we process this further & I'll close this issue off in a few. 

Regards,

Ben.

**Comment by macmule** [comment]
Reopening as @bp on slack is seeing the same.

Looks like domain lookup failing as dig result does not contain an answer section, but an authority section.

**Comment by macmule** [comment]
```
; <<>> DiG 9.8.3-P1 <<>> +time=2 +tries=1 -t srv _ldap._tcp.company.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30296
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;_ldap._tcp.company.com.    IN    SRV

;; AUTHORITY SECTION:
company.com.    3600    IN    SOA    NS87.WORLDNIC.com. namehost.WORLDNIC.com. 116032214 10800 3600 604800 3600

;; Query time: 5 msec
;; SERVER: 172.20.10.1#53(172.20.10.1)
;; WHEN: Tue Mar 22 17:01:19 2016
;; MSG SIZE  rcvd: 103
```

Example from @bp

What ADPassMon expects:

```
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.8.3-P1 <<>> +time=2 +tries=1 -t srv _ldap._tcp.pretendco.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13329
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 31, AUTHORITY: 0, ADDITIONAL: 25

;; QUESTION SECTION:
;_ldap._tcp.pretendco.com.    IN    SRV

;; ANSWER SECTION:
_ldap._tcp.pretendco.com. 600    IN    SRV    0 100 389 dc-04.pretendco.com.

;; ADDITIONAL SECTION:
dc-04.pretendco.com.    3600    IN    A    10.1.2.16
```

**Comment by macmule** [comment]
So, this issue is due to some SSL VPN's causing ADPassMon to have issues looking up details etc.

Currently, I'll not be able to test anything in relation to this. So will close off for now, sorry folks.
