### ISSUE TITLE
Application Signing (Gatekeeper)?

### ISSUE THREAD

**Issue by mberardinelli** [macmule/ADPassMon#46]
Hello! 
We're looking into deploying this to our staff laptops, however, in testing I noticed that Gatekeeper stops the first-time run since the app is not in the "identified developers" list. I was wondering if there is a possibility of this app being signed in the future to alleviate this issue? We really don't want to disable Gatekeeper for our staff machines.
Thanks!
![screen shot 2016-01-26 at 10 39 43 am](https://cloud.githubusercontent.com/assets/16901434/12585253/2a56777a-c419-11e5-8e19-352eedfe3c43.png)

**Comment by macmule** [comment]
@mberardinelli how are you planning on rolling this out? We have GateKeeper enabled & deploying via either a custom PKG through Casper or the AutoPKG recipe we do not have those prompts.

It only happens with manual downloads.

**Comment by mberardinelli** [comment]
We’re hoping to deploy via ARD to specific staff machines, so a PKG would be ideal actually. Is there one available for download somewhere?

Thanks,

Matt Berardinelli
Computer Technician
Berlin Public Schools IT Dept.
mberardinelli@berlinschools.org mailto:mberardinelli@berlinschools.org
Phone: (860) 828-6577 x2311

Log a Help Desk Ticket http://helpdesk.berlinschools.org/ (In-District Only)

**Comment by macmule** [comment]
@mberardinelli There's one via AutoPKG, else you could make your own.

I'm not certain if ARD installed stops the prompts, have you tried?

**Comment by mberardinelli** [comment]
If I copy the .app over via ARD or otherwise, I get the prompt on first launch.

Matt Berardinelli
Computer Technician
Berlin Public Schools IT Dept.
mberardinelli@berlinschools.org mailto:mberardinelli@berlinschools.org
Phone: (860) 828-6577 x2311

Log a Help Desk Ticket http://helpdesk.berlinschools.org/ (In-District Only)

**Comment by macmule** [comment]
@mberardinelli One last thing to do would be sign it yourself.

I may add signing in the future, but might be a few months away.

**Comment by macmule** [comment]
I'm going to re-open this, as with my new job I'll have to get a new developer cert for macmule so will revisit it then.

**Comment by macmule** [comment]
@mberardinelli, does this help? https://github.com/macmule/ADPassMon/wiki/Deployment#gatekeeper

**Comment by macmule** [comment]
Closing this off.

I'm going to do one more release, (2.21.0), but will still not sign the app as if I did.. the cert would expire within a year & the idea of one more release is to give folks to transition to NoMAD.
