### ISSUE TITLE
Feature Request: Check for Updates

### ISSUE THREAD

**Issue by steven-j-klein** [macmule/ADPassMon#48]
I've been running a version of ADPM that's several months out of date (v 2.20.10).

I would have downloaded a newer version if I'd been aware that a newer version existed. But I'm not in the habit of visiting [Github](https://github.com/macmule/ADPassMon/releases) just to check for updates.

There are several ways updates could be handled. In order from simplest to most complex:
1. A menu item "Check for Updates…" that lets me manually check for updates from within ADPM.
2. Automatically check for updates, and display a notification if an update is found.
3. Same as 2, but it should be an option that can be turned on/off in preferences. (Many of the users I support can't install updates, so notifications would just be annoying to them.)
4. Self-installing updates. ("A newer version of ADPassMon is available. Would you like to install it?")

I don't know how difficult it would be to implement this request, but I think update notifications are an important feature for any app. I'd be pretty happy just to have # 1 (the menu item).

**Comment by macmule** [comment]
@steven-j-klein I'd prefer using AutoPKG to get the latest.

I'm wary of offering in-app-updates due to potential client side impact.

Sparkle (http://sparkle-project.org) could be used to do the updates, but as I said, I rather have us push things out & instead leave it to the admin to test & rollout.

**Comment by gmarnin** [comment]
+1 for autopkg. `autopkg search adpassmon`

**Comment by grahamgilbert** [comment]
I would rather my users _didn't_ know about updates. As an admin, it's my responsibility to deploy updates, not theirs. So, another +1 for autopkg.

**Comment by steven-j-klein** [comment]
@grahamgilbert: Yes, as admins, it's our responsibility to deploy updates.

But we're not psychic —we still need to be made aware of updates.

I could manually check for updates, but given the amount of computing power I have at my fingertips, it seems silly to _not_ automate at least part of the process.

I'd be happy to subscribe to a mailing list that notified me of updates. I suppose I could script something to auto-check for updates, but I'd like to think there's a better solution.

Certainly I not the only one here who wants to me notified of updates, am I?

**Comment by pmbuko** [comment]
This is precisely what [AutoPKG](https://github.com/autopkg/autopkg) does for you.

**Comment by macmule** [comment]
Closing this off as we're not looking at adding this.
