### ISSUE TITLE
Use without AD?

### ISSUE THREAD

**Issue by unsoluble** [macmule/ADPassMon#51]
We're not in an AD environment here (OD-only), but this tool looks like it might be the best way to fix the rampant locked-local-items-keychain thing for our users. The app doesn't appear to do anything on launch for me (under 10.11.3) — nothing shows up in the menubar, anyway. Does it not work at all if it doesn't detect an AD account?

If that's the case, is there any way to use the keychain-fixing part separately in this scenario?

Thanks!

**Comment by jardhug** [comment]
haven't used it myself but you could try Keychain Minder?

https://github.com/google/macops-keychainminder

**Comment by unsoluble** [comment]
Hmm! Maybe? Unclear whether it'll address the locked Local Items keychain or not, but I'll dig into it a bit, thanks.

What'd really be best in our context (middle school) is a script that can simply be run against (or from within) a user's account when necessary, as opposed to a thing that's monitoring constantly. Might try to pull the relevant bits from the ADPassMon source into something standalone, maybe...

**Comment by macmule** [comment]
@unsoluble That will update the local items keychain & will be able to check if locked I believe.

Their method is somethingI hope to add at some point to this app.

**Comment by macmule** [comment]
Added, "wontfix" label for now & leaving open for visibility.

OD & non-bound is something I'd like to add, but those will be after moving ADPassMon to python.

**Comment by unsoluble** [comment]
Sounds good. Thanks!

**Comment by macmule** [comment]
Closing off, but if here & looking for ADPassMon sans the AD. Have a look at: https://gitlab.com/Mactroll/NoMAD
