### ISSUE TITLE
Bring to front on login

### ISSUE THREAD

**Issue by SillySalamander** [macmule/ADPassMon#56]
ADpassmon assists in fixing and extremely annoying problem where the local items keychain does not update sometimes when a user updates their password. Our passwords expire every 2 months so you can imagine how annoying that gets. 

When the issue occurs for one of our users they will login, see the osx notification that the keychain cannot be unlocked, and then they usually end up saying "continue login" :[

Now, ADpassmon (i have set as a launchagent) launches and checks to see if the local items keychain unlocks, but the "your keychain is locked" dialogue appears **under** all of the "xxxxx wants to use the local items keychain" osx prompts. My users never make it to the ADpassmon box because it is not in the foreground. 

**Is there any way to suppress the OSX notifications or make ADpassmon appear before or in front of them?** If the only box that came up was ADpassmon life would be so easy.

Thank you very much for the time and effort put into this. Apple and Microsoft should have this worked out between themselves but we all know thats not happening

**Comment by SillySalamander** [comment]
<img width="688" alt="screen shot 2016-03-10 at 11 40 39 am" src="https://cloud.githubusercontent.com/assets/10839110/13682041/f5680146-e6b4-11e5-8b45-4185cd0dbb6b.png">

**Comment by macmule** [comment]
@SillySalamander yep. I'm not 100% sure how best to deal with that unless ADPassMon becomes an auth plugin like https://github.com/google/macops-keychainminder.

I'll keep looking however.

**Comment by macmule** [comment]
Maybe: http://macscripter.net/viewtopic.php?pid=183387#p183387

(Adding to issue for testing)

**Comment by SillySalamander** [comment]
hey this is great thanks a ton I'll try them out and report back

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
