### ISSUE TITLE
Unnecessary executables in app bundle

### ISSUE THREAD

**Issue by homebysix** [macmule/ADPassMon#57]
There are three files in the ADPassMon bundle that have executable permission, but don't require such permission. Here are the files, as reported by RB App Checker:

![screen shot 2016-03-17 at 11 36 33 am](https://cloud.githubusercontent.com/assets/7801391/13857022/315f3b1c-ec35-11e5-87ee-87b813e2917d.png)

**Comment by macmule** [comment]
Kinda need Info.plist!

The app is not going to be signed, but is odd to see the _CodeSignature stuff there.

PkgInfo seems to come as a part of the project build, leaving for now as tbh.. not sure how to stop that!

**Comment by homebysix** [comment]
I'm not suggesting removing the files — simply making them non-executable. (`chmod -x foo`)

**Comment by macmule** [comment]
I found the pkginfo file. Will see if I can kill off the others etc.

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
