### ISSUE TITLE
Not an ADPM issue, but an issue inspired by ADPM

### ISSUE THREAD

**Issue by steven-j-klein** [macmule/ADPassMon#58]
_If this is the wrong place to make this request, please point me in the appropriate direction._

**Short version:**
I know that ADPassMon is a Mac-only app, but is there a similar Windows utility? An app that can display (in the systray) days until password expiration?

**Long version:**
My windows users have noticed Mac users have this lovely tool in their menubar to show them when their passwords expire. (I suspect they think it's a feature of OS X.)

Several have now asked me how they can get that on their Windows 7 PCs. I've just spent 10 minutes Googling for a solution, but I can't find one.

Asking my fellow Mac admins might not be the best strategy for asking for Windows help, but asking in the ADPassMon group has the advantage of me not having to first explain what ADPassMon does.

Should I just tell those Windows users to switch to Mac?

**Comment by macmule** [comment]
Lovely question!

No idea about a solution for the folks on windows. Sorry!
