### ISSUE TITLE
Can’t make «class ocid» id «data optr00000000904D70F1EF7F0000» into type integer. (error -1700)

### ISSUE THREAD

**Issue by entusdictus** [macmule/ADPassMon#59]
ADPassMon 2.20.19 launches only once per user on multiple machines. First launch is all okay, the second launch produces the following error in console:

05.04.16 13:18:44,455 ADPassMon[13480]: **\* -[ADPassMonAppDelegate applicationWillFinishLaunching:]: Can’t make «class ocid» id «data optr00000000904D70F1EF7F0000» into type integer. (error -1700)

**Comment by macmule** [comment]
Odd.

What OS's?

Anything else in the logs?

How was the app packaged & deployed?

**Comment by entusdictus** [comment]
I found the reason for this issue. ADPassMon 2.20.19 seems to corrupt the org.pmbuko.adpassmon.plist. 
The key expireDateUnix is incorrectly formatted.
<key>expireDateUnix</key>
<string>1,4608736</string>

when you remove the "," from the string, ADPassMon will work again.

**Comment by entusdictus** [comment]
OS is 10.11.4, app was packaged with Composer and deployed with the JSS.

**Comment by macmule** [comment]
@entusdictus odd.. What language is the OS running when this happens?

**Comment by entusdictus** [comment]
This OS is running in German.

**Comment by macmule** [comment]
Bugger. 

AppleScript is pseudo American English. So I think it's having issues with the German localisation.

I'll have a play & will put an update out.

**Comment by lumaforge** [comment]
Ran into the same localization issue with a Spanish version of OS X and trying to not have it auto-translate the name of the Network Adapter in the System Prefs so it would match what is seen in the 'networksetup' command line program.

**Comment by tommywo** [comment]
I have the same issue on English OSX 10.11.5. Breaking change was introduced between 1498c1d and  43982d7

**Comment by macmule** [comment]
Can you folks run the below & advise what is returned?

`echo '(131258737778620155/10000000)-11644473600' | /usr/bin/bc`

@tommywo, @entusdictus, @lumaforge

**Comment by macmule** [comment]
@entusdictus, @lumaforge, @tommywo 

Can you test the below? I think the issue was with NSNumberFormatter.. I think

[ADPassMon.zip](https://github.com/macmule/ADPassMon/files/560206/ADPassMon.zip)

**Comment by entusdictus** [comment]
@macmule, the result is:
myuser$ echo '(131258737778620155/10000000)-11644473600' | /usr/bin/bc
1481400177

**Comment by macmule** [comment]
@entusdictus can you test: **https://github.com/macmule/ADPassMon/files/560206/ADPassMon.zip**

**Comment by entusdictus** [comment]
First it seems to work, but when configuring with "manual" settings, the status window will keep the status "Working..."
We have to use the "manual" setting in this environment, because automatic displays a different password runtime (long story short: automatic is technically correct, but customer has a weird construct for their passwords so this cannot be used).

**Comment by macmule** [comment]
@entusdictus thanks! Progress at least :) 

I think i know why the "working.." hang is occurring & will look into that shortly

**Comment by macmule** [comment]
@entusdictus I was wrong about the "working..." issue, can you let me know what OS, what language & post the org.pmbuko.adpassmon.plist?

**Comment by entusdictus** [comment]
OS is 10.12.1 16B2555. Language is German. 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>accTest</key>
    <string>0</string>
    <key>allowPasswordChange</key>
    <false/>
    <key>enableNotifications</key>
    <true/>
    <key>expireAge</key>
    <integer>30</integer>
    <key>expireDateUnix</key>
    <string>1484802446</string>
    <key>isBehaviour2Enabled</key>
    <integer>0</integer>
    <key>menu_title</key>
    <string>75d</string>
    <key>selectedBehaviour</key>
    <integer>1</integer>
    <key>selectedMethod</key>
    <integer>1</integer>
    <key>tooltip</key>
    <string>Your password expires
Thu Jan 19 06:07:26 CET 2017</string>
    <key>warningDays</key>
    <integer>7</integer>
</dict>
</plist>
```

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/154

**Comment by entusdictus** [comment]
@macmule, looks good so far! 👍

**Comment by macmule** [comment]
@entusdictus awesome.. I'll close this off for now :)
