### ISSUE TITLE
10.10.5 Not Respecting Fine Grained Password Policy

### ISSUE THREAD

**Issue by gmarnin** [macmule/ADPassMon#6]
This isn't really an issue with ADPassMon but it is closely related to it.

So my 10.10.5 Mac has a fine grained password policy. When I login I’m getting warned by the OS that my password expires in 10 days (and I should change it) which isn’t correct. ADPassMon reports 65 days which is correct. Yeah for ADPassMod for respecting the policy! Is it a known issue that the Mac doesn't respect a fine grained password policy from AD? How is the Mac calculating the password expiry? Any thoughts or known workarounds for turning off the OS warnings or fine tuning the settings? 

Thanks for merging the forks!

**Comment by pmbuko** [comment]
[This is the line that gets the stored expiration date from AD](https://github.com/macmule/ADPassMon/blob/master/ADPassMon/ADPassMonAppDelegate.applescript#L685). The rest of the `easyMethod` code block converts that number to a UNIX date. [Here's a bash script](https://gist.github.com/pmbuko/0f8c6904def80cbb1265) that does more or less the same thing.

I'm not sure about the OS's warning and whether it respects fine-grained password policy, though.
