### ISSUE TITLE
eDSRecordNotFound (Error 56)

### ISSUE THREAD

**Issue by monaronyc** [macmule/ADPassMon#62]
Hi Group!

Getting this weird string in Console when launching version 2.20.19 on some but not all of our folks. Worked in version 2.20.15. Here's the string:

4:42:21 PM ADPassMon: **\* -[ADPassMonAppDelegate applicationWillFinishLaunching:]: <dscl_cmd> DS Error: -14136 (eDSRecordNotFound) (error56)

Any thoughts? THANKS!

**Comment by macmule** [comment]
Hmm. 

Can you rebind a client that's seeing the error & see if that helps?

**Comment by monaronyc** [comment]
I tried that. Tried it one more time on another machine just to be sure. Same problem. Same error too. Does the fact that maybe these folks have spaces between their AD login names?

**Comment by monaronyc** [comment]
Just tried this on a new user. At first launch in console we get:
1:44:20 PM ADPassMon: Running on 0S 10.11.x
1:44:20 PM ADPassMon: Something went wrong, can't find the current user in any directory service.
1:44:20 PM ADPassMon:   Stopping.

I wonder if it has anything to do with the fact these users have spaces between their names.

**Comment by ekelling** [comment]
I'm having the same issue... spaces in the username.

**Comment by monaronyc** [comment]
Would it be possible to address the problem with folks who have spaces between their AD login names? Had another one today we couldn't set up.

**Comment by macmule** [comment]
@monaronyc The issue I have is being able to test ADPassMon in an environment that would follows the same naming convention.

I currently do not have an AD, let alone one with spaces in names. I'll looking to build a test AD (time allowing).

**Comment by monaronyc** [comment]
@macmule if you'd like me to help with testing, no problem. Send me what you have to test. @pmbuko (Peter) has helped us in the past with this very same problem. Maybe reach out to him? He was able to fix it in a jiffy!

**Comment by macmule** [comment]
Something to test!

**Comment by macmule** [comment]
@monaronyc & @ekelling Please test the below, it's a very early build of next release.

Seems to work in my testing.

[ADPassMon.zip](https://github.com/macmule/ADPassMon/files/560193/ADPassMon.zip)

**Comment by monaronyc** [comment]
EXCELLENT! We'll try it now. Stand by...

**Comment by macmule** [comment]
@monaronyc any update?

**Comment by monaronyc** [comment]
YES! Thank you by the way...! So far so good. And it looks like the problem with the space between the users AD name login was fixed as well. We also tried this in our Sierra environment. Working as well!

**Comment by macmule** [comment]
@monaronyc awesome.. some more stuff is coming :)
