### ISSUE TITLE
Forcing manual mode when there's no password expiry

### ISSUE THREAD

**Issue by waisanen** [macmule/ADPassMon#63]
We have a non-standard setup that I've been trying to configure ADPassMon around.  We have an identity management system that handles all password changes and expiry and pushes this down to all affected systems, including Active Directory.

Password expiry itself is not set on the AD side.  So, it seems your code is doing a check in AD for password expiry, sees it's not set, then skips/ignores the selectedMethod and expireAge keys entirely.  Disclaimer: my AppleScript is very rusty and I may not be entirely understanding all your code.  ;)

Is there a key I'm missing or set incorrectly in my plist that would force manual mode or is the logic in your code part of the cause?

[org.pmbuko.ADPassMon.txt](https://github.com/macmule/ADPassMon/files/226711/org.pmbuko.ADPassMon.txt)

**Comment by macmule** [comment]
@waisanen, correct. Currently ADPassMon checks AD.

I'm working on a different version of ADPassMon, just wondering how/where the Mac client would see the expiry for your org?

**Comment by waisanen** [comment]
The practice in our org is the client doesn't see the expiry at all (the flag is not set in AD).  Identity management emails the end-user several nags that their password is about to expire, then pushes down a randomized password to all linked accounts if they fail to change it.

However, it does appear the maxPwdAge is published so a little quick math between that and when the password was last set could give enough information to a user about when the password will expire.  I don't mind manually setting the maximum password age in ADPassMon via plist if I could get it to stick.  Configuring via it's preference pane works just fine.

**Comment by macmule** [comment]
I'd suggest looking at: https://gitlab.com/Mactroll/NoMAD
