### ISSUE TITLE
10 Million?

### ISSUE THREAD

**Issue by monaronyc** [macmule/ADPassMon#64]
What's up Group! Not sure what happened but all of the sudden, i have folks who's expiration number is in the tens of millions. 10523501d to be exact on one! Got the log for this. Wondering if you can see something:

4/27/16 2:41:14.583 PM ADPassMon[17138]: Running on OS 10.11.x
4/27/16 2:41:14.685 PM ADPassMon[17138]: Running under a locally cached network account.
4/27/16 2:41:14.692 PM ADPassMon[17138]: Native password method selected
4/27/16 2:41:14.692 PM ADPassMon[17138]: Testing Universal Access settings…
4/27/16 2:41:14.692 PM ADPassMon[17138]:   Enabled
4/27/16 2:41:14.850 PM ADPassMon[17138]: Domain reachable.
4/27/16 2:41:14.850 PM ADPassMon[17138]: Testing if password can expire…
4/27/16 2:41:14.890 PM ADPassMon[17138]:   Password does expire.
4/27/16 2:41:14.924 PM ADPassMon[17138]: Domain reachable.
4/27/16 2:41:14.925 PM ADPassMon[17138]: Starting auto process…
4/27/16 2:41:14.925 PM ADPassMon[17138]:   Found expireDateUnix in plist: -2.147483648E+9
4/27/16 2:41:15.378 PM ADPassMon[17138]:   Got expireDateUnix: 910692730085
4/27/16 2:41:15.378 PM ADPassMon[17138]:   Using msDS method
4/27/16 2:41:15.390 PM ADPassMon[17138]:     daysUntilExp: 1.052350633808E+7
4/27/16 2:41:15.392 PM ADPassMon[17138]: Native password method selected
4/27/16 2:41:15.392 PM ADPassMon[17138]: Testing Universal Access settings…
4/27/16 2:41:15.392 PM ADPassMon[17138]:   Enabled
4/27/16 2:41:15.392 PM ADPassMon[17138]: Testing Keychain Lock state...
4/27/16 2:41:15.426 PM ADPassMon[17138]:   Keychain unlocked...

**Comment by macmule** [comment]
Hmm.. sounds like your expiry might be being set via Group Policy or something. (i.e. something ADPassMon is not able to detect).. 

Did you try manual mode? https://github.com/macmule/ADPassMon/wiki#auto-or-manual-mode

**Comment by macmule** [comment]
Closing as manual mode should be the fix here.
