### ISSUE TITLE
AdPassMon - Built in Password change Issue - 

### ISSUE THREAD

**Issue by thesling1** [macmule/ADPassMon#65]
Hello,

I am very impressed by this tool.  Being able to advise users of there pending password change is golden.  

OSX El Capitan 10.11.3

I am hoping to be able to utilize tools built in password dialog box which apparently will update the keychain.  However it is not working.  I get a message that states:

Password change failed.  Please try again.
In system logs I see:  
ADPassMon[334] All password fields populated & new & veryify match...
ADPassMon[334] Attempting user password change..
ADPassMon[334] Password change failed.

Please help!  I would investigate changing settings on the domain to help this work properly!

Thank you,
Tony H.

**Comment by thesling1** [comment]
I tried on another mac... this time the password change tool presented no error.

However... there was no change to the password.

**Comment by macmule** [comment]
Can you try this on one of those Macs?

`dscl . -passwd /Users/$USER oldPassword newPassword`

replacing oldPassword & newPassword as needed.

**Comment by thesling1** [comment]
Thank you.

Can you advise what this does?  Or is this a test?

**Comment by macmule** [comment]
Hi @thesling1, 

It what ADPassMon does to change the password & is a test.

**Comment by macmule** [comment]
@thesling1 Please see: https://github.com/macmule/ADPassMon/issues/68#issuecomment-219399304

Are you running ADPassMon under a local account with same username as it's AD counterpart?

**Comment by apizz** [comment]
I'm having this same issue as well.  I used the tccutil.py tool to programmatically add ADPassMon to the list of apps that have Accessibility control so users aren't prompted for a password to setup at first launch, but I too get the can't change password error.  Redeploying the app without our custom preferences file also produces the same error.

**Comment by apizz** [comment]
Turns out I'm just an idiot testing local mobile accounts that in Active Directory did not have the ability for the user to change the password ... my bad.

**Comment by SachinParmar** [comment]
I'm having this issue right now, can't figure what's happening my progress is here https://jamfnation.jamfsoftware.com/discussion.html?id=20657 worked perfectly before 10.11.4-6

**Comment by macmule** [comment]
As posted on JAMFNation: 

Check your domains password change policy. 

The error is saying that you've failed some criteria, is there maybe a part of the policy that doesn't allow changes within X days?

**Comment by macmule** [comment]
Closing this off for now, presuming it's an AD issue.. either communicating to AD client side, or a policy is in the way.
