### ISSUE TITLE
Make preference items greyed out if managed via profile or MCX

### ISSUE THREAD

**Issue by pboushy** [macmule/ADPassMon#66]
It would be helpful to either grey out, or hide a preference in the Preferences window if the preference is enforced by Profiles or MCX.

**Comment by macmule** [comment]
@prbsparx Why not lock out the preference window? https://github.com/macmule/ADPassMon/wiki/Customization#lock-out-the-preferences-window

**Comment by pboushy** [comment]
The difference is enforcing a single preference item. For instance, I might want to set the password expiration refresh to 12 hours and not allow the end user to change that, but I do want them to be able to enable notifications and set how far ahead it notifies them.
I was actually going to look into this tonight and chat with the group in Slack about how it could be done and what the best method might be.

**Comment by macmule** [comment]
This can be done with CFPrefs:

``` #!/usr/bin/python

import CoreFoundation

domain = 'com.apple.Spotlight'
key = 'parsecEnabled'

key_value = CoreFoundation.CFPreferencesCopyAppValue(key, domain)
print 'Key Value = ', key_value

key_forced = CoreFoundation.CFPreferencesAppValueIsForced(key, domain) 
print 'Key Forced = ', key_forced
```

with the "CFPreferencesAppValueIsForced" key advising if forced via a profile.

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
