### ISSUE TITLE
"Assistive Access" prompt for password comes up on EVERY login - is that normal ?

### ISSUE THREAD

**Issue by jmnugent** [macmule/ADPassMon#70]
Hi.. I'm new to github.. so I may not be doing this right!?
I installed ADPassMon. .and I love it... but the "Assistive Access" popup prompting for my Password.. is happening at EVERY login. Is that normal ? (note:..  I had to set to "Manual" to fix the "10million days" problem).

**Comment by jardhug** [comment]
not sure if this is it but have you tried this?

https://github.com/macmule/ADPassMon/wiki/Customization#skip-accessibility-check

**Comment by jmnugent** [comment]
Thanks danprk !... I will try that.. but I guess I assumed the Accessibility-check was a necessary/fundamental component of ADPassMon needed to actually work.

**Comment by macmule** [comment]
@danprk Thanks!

@jmnugent did that work?

**Comment by mopenmind** [comment]
I have the same issue; The dialog "ADPassMon's "Change Password" feature requires assistive  access to open the password panel. Enable it now? (requires password)" appears on every login although I allowed access before. As I understand, skipping the check does not actually allow access or does it?

**Comment by macmule** [comment]
@mopenmind, is this on 10.12?

Apple have SIP protected the Assistive Devices DB, so probably why.

I'm hoping to spend some time on ADPassMon & 10.12 this week, but we'll probably need to only allow password changes via ADPassMon.

**Comment by mopenmind** [comment]
Exactly, this is on 10.12.

**Comment by macmule** [comment]
The change i'm going to make is that on 10.12 you'll need to use the inbuilt password change mechanism.

**Comment by macmule** [comment]
@mopenmind I cannot recreate this on 10.12.x, how are you launching ADPassMon?

**Comment by mopenmind** [comment]
@macmule I just launch ADPassMon via Finder. Since I disabled it using
`defaults write org.pmbuko.ADPassMon accTest 0` the message does not appear anymore.

**Comment by macmule** [comment]
Thanks @mopenmind, i'lol have another look.

**Comment by macmule** [comment]
Ok.. Closing this off.

10.12 is fine with this.

The issue is behaviour1 & an admin account without accTest set to 0 will ask for admin password for assistive devices. Once password entered you'll not see it again.

Or as per @danprk's recommendation: 

https://github.com/macmule/ADPassMon/wiki/Customization#skip-accessibility-check

**Comment by macmule** [comment]
Reopening. Just had another report.

Will look at not running accTest if on 10.12 & seeing if I can recreate the prompt showing even after entering admin credentials.

CC @bwiessner on Slack.

**Comment by macmule** [comment]
OK.. so skipping should mean that the app will not prompt till next launch.

To completely disable: https://github.com/macmule/ADPassMon/wiki/Customization#skip-accessibility-check

(as of build 162)
