### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by martinb-1995** [macmule/ADPassMon#71]
I'm testing AdPassMon on a Macbook Pro to see how it can be integrated within the existing Active Directory system that I'm currently using.

First I bound the machine to the AD system, I then created a test account in AD for testing purposes, logged in to the test machine (created a mobile account) when prompted. But when I try to change the password (using the AdPassMon interface); the following error is displayed:

"Password change failed. Please try again".

I've tried unbinding and re-binding the test machine from AD, restarting the machine, I've been entering the existing and new password correctly, and the new password adheres to Active Directory's password policy. Any ideas?

**Comment by apizz** [comment]
I had a similar issue, but it was because the test account I was using had 1) password never expires and 2) user cannot change password.  Are either of these settings enabled for the AD account you're using?

Also, if the user is not an admin account on the machine you won't see the prompt to add ADPassMon to the list of apps that can control Accessibility.

**Comment by martinb-1995** [comment]
Thanks for the reply apizz,

No, neither of those settings are enabled on the AD account and the user isn't an Administrator.

**Comment by mariuslangz** [comment]
Did you try to change the password the same day as you created the test account? 
I've done the same thing before, and found that the "minimum password age" policy was set to 1 day which meant I had to wait 24 hours from initially creating the account to being able to change it as the actual user. 
Admins which can reset passwords on behalf of users directly in AD will not be stopped by this policy.

**Comment by macmule** [comment]
Closing off, as presuming it's the issue that @mariuslangz mentioned.
