### ISSUE TITLE
Incorrect version in 2.20.20 source

### ISSUE THREAD

**Issue by bjmd** [macmule/ADPassMon#72]
Hey.

I am looking into using version 2.20.20 but when downloading the source its still listed as 2.20.19. 

Can you confirm if that is meant to be or if its just a typo and should read .20?

**Comment by macmule** [comment]
Hi @bmillington,

2.20.20 is a pre-release, with source not published yet.. You can download a compiled app from: https://github.com/macmule/ADPassMon/releases/tag/2.20.20

**Comment by bjmd** [comment]
@macmule wow that was a quick reply! 

OK thanks, that makes sense. Do you know when the source will be published? I have made changes to the code for our environment so I can't just run the compiled app.

**Comment by macmule** [comment]
@bmillington there is a future release coming "soon".. Needs testing on 10.12.

**Comment by bjmd** [comment]
@macmule: We will happily be your guinea pig if needed... :-)

In the mean time I will see if I can port the changes across manually, if I can figure out what they are!

**Comment by macmule** [comment]
@bmillington Ok.. well just committed the 2.20.20 source.
https://github.com/macmule/ADPassMon/commit/cf59dc95cfd7e4ccd54137243f0103125c1d2e29

TBH, I can't remember what state it's in.. hence not releasing.

**Comment by bjmd** [comment]
OK thats cool, no problem.

On 15 September 2016 at 13:40:45, macmule (notifications@github.com) wrote:

@bmillington https://github.com/bmillington Ok.. well just committed the
2.20.20 source.
cf59dc9
https://github.com/macmule/ADPassMon/commit/cf59dc95cfd7e4ccd54137243f0103125c1d2e29

TBH, I can't remember what state it's in.. hence not releasing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/macmule/ADPassMon/issues/72#issuecomment-247316891,
or mute
the thread
