### ISSUE TITLE
ADpassmon icon "disappears" from the status menu

### ISSUE THREAD

**Issue by GrandDanois** [macmule/ADPassMon#73]
Hi in my company we have several Mac users inc. myself, who are very happy ADpassmon users.
Unfortunately some of the users are starting to experience that the ADpassmon icon strangely disappears from the status menu in the top right corner, and when its gone - notting can bring it back.
I have tried to uninstall, restart, try an older version etc. nothing works. could you please help before all my hair turns gray? :/ :)

**Comment by macmule** [comment]
Hi @GrandDanois, can you see anything in the system.log when you try to launch ADPassMon?

**Comment by GrandDanois** [comment]
Hi @macmule this is from a user with the specific problem

Here are the logs from Console, regarding shutting down, starting the computer and starting the application from Programs.

// Shut down computer, diagnostic and usage messages
2016-09-21 09:43:37,717 diagnostics_agent[381]: com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: ADPassMon
com.apple.message.signature2: org.pmbuko.ADPassMon ||| 2.20.20 (145)
com.apple.message.value: 1124
com.apple.message.value2: 0
com.apple.message.value3: 0
com.apple.message.value4: 0
com.apple.message.value5: 0
com.apple.message.value6: 0
com.apple.message.value7: 0
com.apple.message.result: NO
com.apple.message.summarize: YES
SenderMachUUID: AA39D707-20FA-3285-BAC6-866FBEECFAEC

2016-09-21 09:43:39,341 diagnostics_agent[381]: com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.signature: ADPassMon
com.apple.message.signature2: org.pmbuko.ADPassMon ||| 2.20.20 (145)
com.apple.message.value: 2
com.apple.message.value2: 0
com.apple.message.value3: 0
com.apple.message.value4: 0
com.apple.message.value5: 0
com.apple.message.value6: 0
com.apple.message.value7: 0
com.apple.message.result: NO
com.apple.message.summarize: YES
SenderMachUUID: AA39D707-20FA-3285-BAC6-866FBEECFAEC

// Start up computer, diagnostic and usage messages
2016-09-21 09:46:43,781 loginwindow[103]: com.apple.message.domain: com.apple.coreservices.applaunch
com.apple.message.path_bucket: 0
com.apple.message.volume_is_network: no
com.apple.message.volume_is_removable: no
com.apple.message.volume_is_ejectable: no
com.apple.message.quarantined: no
com.apple.message.volume_is_root: yes
com.apple.message.volume_is_disk_image: no
com.apple.message.bundle_identifier: org.pmbuko.ADPassMon
com.apple.message.bundle_version: 145
com.apple.message.bundle_short_version: 2.20.20
SenderMachUUID: 7BF2C06A-4D7D-353B-A253-00EA52059508

// Start up computer, All messages
2016-09-21 09:46:44,144 ADPassMon[492]: Running on OS 10.11.x
2016-09-21 09:46:44,153 ADPassMon[492]: **\* -[ADPassMonAppDelegate applicationWillFinishLaunching:]: Can’t make «class ocid» id «data optr000000003025E0FA867F0000» into type integer. (error -1700)

// Start the application from Programs, diagnostic and usage messages
2016-09-21 09:49:56,394 Finder[383]: OSActivityID: 0x0000000000002939
com.apple.message.domain: com.apple.coreservices.applaunch
com.apple.message.path_bucket: 0
com.apple.message.quarantined: no
com.apple.message.volume_is_network: no
com.apple.message.volume_is_removable: no
com.apple.message.volume_is_ejectable: no
com.apple.message.volume_is_root: yes
com.apple.message.volume_is_disk_image: no
com.apple.message.bundle_identifier: org.pmbuko.ADPassMon
com.apple.message.bundle_version: 145
com.apple.message.bundle_short_version: 2.20.20
SenderMachUUID: 88848909-83E1-39AF-9B8E-A535DEC3B3E8

**Comment by jardhug** [comment]
Are you using a configuration profile?

**Comment by GrandDanois** [comment]
We are using profile manager?

**Comment by jardhug** [comment]
Are you setting the apps preferences with a plist?

**Comment by GrandDanois** [comment]
Nope don't even know how to do that :)

**Comment by jardhug** [comment]
What if you open terminal and type in 

killall ADPassMon

And then relaunch?

**Comment by GrandDanois** [comment]
@danprk t doesn’t change anything. Console with all messages:

2016-09-22 13:33:43,809 com.apple.xpc.launchd[1]: (org.pmbuko.ADPassMon.63392[3589]) Service exited due to signal: Terminated: 15
2016-09-22 13:33:52,325 ADPassMon[3602]: Running on OS 10.11.x
2016-09-22 13:33:52,333 ADPassMon[3602]: **\* -[ADPassMonAppDelegate applicationWillFinishLaunching:]: Can’t make «class ocid» id «data optr000000000023F041C67F0000» into type integer. (error -1700)

**Comment by jardhug** [comment]
wiped the plist org.pmbuko.ADPassMon.plist and restarted?

**Comment by GrandDanois** [comment]
@danprk where do I locate that plist?

**Comment by pmbuko** [comment]
You can do `defaults delete org.pmbuko.ADPassMon.plist` and `sudo defaults delete org.pmbuko.ADPassMon.plist` to wipe all traces of it.

**Comment by GrandDanois** [comment]
Hi @pmbuko it looks like it might have solved the issue - thank you very much 👍 
@macmule If I may suggest an idea for a forthcoming update, it would be to make an uninstaller for ADpassmon
