### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by simonpie** [macmule/ADPassMon#74]
Hello,

I tried ADPassMon from brew, but the application would not launch and it does that silently.  Nothing in `/var/log/system.log`.  So I decided to download the code and compile it.  It compiles it fine, but it stops immediately with the following messages :

```
2016-10-03 08:24:07.352 ADPassMon[52874:18677404] Running on OS 10.11.x
2016-10-03 08:24:07.482 ADPassMon[52874:18677404] Something went wrong, found the current user in the search path but the schema doesn't match.
2016-10-03 08:24:07.482 ADPassMon[52874:18677404]   Stopping.
```

I am running the software on a 10.11.6 macpro.  I have a local account, but the mac is connected to an AD.

**Comment by jardhug** [comment]
ADPassMon only works if your machine is bound to AD. You might want to try something like https://gitlab.com/Mactroll/NoMAD

though its only in Beta

**Comment by simonpie** [comment]
The machine is bound to the AD.  The account I use is local.

**Comment by simonpie** [comment]
@danprk 
Your suggestion for NoMAD worked perfectly for my use case (just changing my password).  Thanks.

**Comment by macmule** [comment]
Cool! thanks @danprk.

Closing off.
