### ISSUE TITLE
New Version does not start

### ISSUE THREAD

**Issue by Tranel** [macmule/ADPassMon#83]
Hi
Like always I copied the new version into the programs folder and if I click it to start nothing happens.  Is there a trick?

**Comment by macmule** [comment]
@Tranel Are you testing the latest beta? https://github.com/macmule/ADPassMon/releases/tag/154

If not, please try that & post the log ~/Library/Logs/ADPassMon.log

**Comment by Tranel** [comment]
Yes. Latest version. And it is not shown in the Menu Bar anymore.

Here is the log.

Tue Nov 8 15:28:46 CET 2016 Launching.....
Tue Nov 8 15:28:46 CET 2016 ADPassMon Version: 2.21.0 (154)
Tue Nov 8 15:28:46 CET 2016 Running on OS 10.12.x
Tue Nov 8 15:28:46 CET 2016 Username: *********
Tue Nov 8 15:28:46 CET 2016 Set number formatter
Tue Nov 8 15:28:46 CET 2016 Registering defaults..
Tue Nov 8 15:28:46 CET 2016 Retrieving defaults..
Tue Nov 8 15:28:46 CET 2016 Running under a locally cached network account.

**Comment by macmule** [comment]
@Tranel odd.. 

Can you:
- Open Console.app, search for "ADPassMon". Open "ADPassMon" & advise of any messages that appear there.
- Copy the output of `defaults read org.pmbuko.adpassmon` here.
- Copy the output of `sudo dsconfigad -show` here

**Comment by jasonsova** [comment]
after installing release 21 it worked for a bit then I installed kerbminder and started seeing the below errors

ADPassMon.log
Tue Nov 8 15:46:26 CST 2016 Launching.....
Tue Nov 8 15:46:26 CST 2016 ADPassMon Version: 2.21.0 (154)
Tue Nov 8 15:46:26 CST 2016 Running on OS 10.11.x
Tue Nov 8 15:46:26 CST 2016 Username: username
Tue Nov 8 15:46:26 CST 2016 Set number formatter
Tue Nov 8 15:46:26 CST 2016 Registering defaults..
Tue Nov 8 15:46:26 CST 2016 Retrieving defaults..
Tue Nov 8 15:46:27 CST 2016 Running under a locally cached network account.

All Messages:
11/8/16 3:46:27.264 PM ADPassMon[849]: **\* -[ADPassMonAppDelegate applicationWillFinishLaunching:]: Finder got an error: Can’t continue logToFile_. (error -1708)

Permissions on ~/Library/logs
drwx------+ 47 username  XXXX\Domain Users    1598 Nov  8 15:48 .
drwx------@ 53 username  XXXX\Domain Users    1802 Nov  7 12:13 ..
-rw-r--r--   1 username  XXXX\Domain Users    6611 Nov  8 15:46 ADPassMon.log

preference file
defaults read org.pmbuko.adpassmon
2016-11-08 16:04:29.728 defaults[1574:18175] 
Domain org.pmbuko.adpassmon does not exist

sudo dsconfigad -show
Active Directory Forest          = corporate.XXXX
Active Directory Domain          = corporate.XXX
Computer Account                 = XXXX$

Advanced Options - User Experience
  Create mobile account at login = Enabled
     Require confirmation        = Disabled
  Force home to startup disk     = Enabled
     Mount home as sharepoint    = Enabled
  Use Windows UNC path for home  = Disabled
     Network protocol to be used = smb
  Default user Shell             = /bin/bash

Advanced Options - Mappings
  Mapping UID to attribute       = not set
  Mapping user GID to attribute  = not set
  Mapping group GID to attribute = not set
  Generate Kerberos authority    = Enabled

Advanced Options - Administrative
  Preferred Domain controller    = not set
  Allowed admin groups           = Domain Admins
  Authentication from any domain = Enabled
  Packet signing                 = allow
  Packet encryption              = allow
  Password change interval       = 30
  Restrict Dynamic DNS updates   = not set
  Namespace mode                 = domain

**Comment by macmule** [comment]
@jasonsova thanks!

From: https://developer.apple.com/library/content/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_error_codes.html

Which version of KerbMinder? 

(For my info). 
-1708 The script doesn’t understand the <message> message. The event was not handled.

**Comment by jasonsova** [comment]
KerbMinder.v1.4b2

**Comment by macmule** [comment]
@tranel are you running KerbMinder too?

**Comment by jasonsova** [comment]
fyi, I just went in and manually deleted all the kerbminder files, preferences, LD and LA’s and ADPassMon came back to life. I then installed the 1.3 of kerbminder and got the same result as the 1.4 pre-release of Kerbminder

**Comment by Tranel** [comment]
Yes, I am running the latest version of KerbMinder too.

**Comment by macmule** [comment]
Perfect! (well not, but from an issue tracking pov it is).

I'll have a look at this & hopefully will have a new build out over the weekend.

**Comment by Tranel** [comment]
I have installed the previous version again and everything works fine. Seems really that the latest version of ADPassMon and KerbMinder do not work together.

**Comment by macmule** [comment]
Hi folks,

I'm going to the KerbMinder support as per: https://github.com/macmule/ADPassMon/issues/84

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/155

**Comment by macmule** [comment]
Closing off a no crash with KerbMinder installed now.
