### ISSUE TITLE
Remove KerbMinder support

### ISSUE THREAD

**Issue by macmule** [macmule/ADPassMon#84]
The support, is only toggling a menu item. 

As per:

https://github.com/macmule/ADPassMon/blob/master/ADPassMon/ADPassMonAppDelegate.applescript#L379

```
    -- Check to see if KerbMinder installed
    on KerbMinderTest_(sender)
        tell application "Finder"
            if exists "/Library/Application Support/crankd/KerbMinder.py" as POSIX file
                set my KerbMinderInstalled to true
                set logMe to "KerbMinder installed..."
                logToFile_(me)
            else
                set my KerbMinderInstalled to false
            end if
        end tell
    end KerbMinderTest_
```

And... https://github.com/macmule/ADPassMon/blob/master/ADPassMon/ADPassMonAppDelegate.applescript#L1506

```    on toggleKerbMinder_(sender)
        if my enableKerbMinder as boolean is true
            set my enableKerbMinder to false
            my statusMenu's itemWithTitle_("Use KerbMinder")'s setState_(0)
            tell defaults to setObject_forKey_(enableKerbMinder, "enableKerbMinder")
            set logMe to "Disabled KerbMinder."
            logToFile_(me)
        else
            set my enableKerbMinder to true
            my statusMenu's itemWithTitle_("Use KerbMinder")'s setState_(1)
            tell defaults to setObject_forKey_(enableKerbMinder, "enableKerbMinder")
            set logMe to "Enabled KerbMinder."
            logToFile_(me)
        end if
    end toggleKerbMinder_
```

So it's largely not needed, & has caused an issue as per: https://github.com/macmule/ADPassMon/issues/83

**Comment by danshaw** [comment]
I apologize for the simplistic question, but does this change here remove compatibility with Kerbminder because the feature is now in ADPM and Kerbminder is not needed anymore? 

The reason I ask is that Kerbminder for us has helped a lot at keeping the Kerberos ticket active and not expire. Without it, the ticket will sometimes expire and to the user it looks like they can still reset their password. We then get sync issues that leads to keychain problems.

It would be great if it did, but I wanted to confirm as we have a lot of users who are currently using KM.

**Comment by macmule** [comment]
@danshaw The issue is the "integration" that seems to be in ADPassMon but actually isn't doing anything.

Running KerbMinder alongside ADPassMon will still work after this change, just the menu item for KerbMinder will disappear from ADPassMon.

Does that make sense?

**Comment by danshaw** [comment]
Ah ok. Makes total sense. What will be the best method moving forward for knowing if Kerbminder is active?

**Comment by macmule** [comment]
@danshaw I have no idea.. ADPassMon's code doesn't show if KerbMinder is active.. just that the file is there.

```
if exists "/Library/Application Support/crankd/KerbMinder.py" as POSIX file
                set my KerbMinderInstalled to true
                set logMe to "KerbMinder installed..."
```

So there never has been any real integration & the latest KerbMinder releases (1.3+) do not leverage ADPassMon's plist anymore.. so they are really 2 separate apps.
