### ISSUE TITLE
Download File Size

### ISSUE THREAD

**Issue by clburlison** [macmule/ADPassMon#9]
Hey Ben,

The [dmg](http://macmule.com/downloads/ADPassMon-2.0.9.dmg) for your compiled app is huge (10 MB). I'm not sure how you are wrapping the app into a dmg but can I recommend the following [wrap-dmg.py](https://github.com/hjuutilainen/adminscripts/blob/master/wrap-dmg.py) script from Hannes. Using this script is the same as Disk Utility > File > New > Disk Image From Folder... with the compressed option. It brings the dmg size down to near 400 KB.

```bash
[clburlison] ADPassMon ○ wrap-dmg.py -ai /Volumes/ADPassMon-2.0.9/ADPassMon.app 

Creating disk image from /Volumes/ADPassMon-2.0.9/ADPassMon.app
---> Done

[clburlison] ADPassMon ○ ls -lh
total 21280
-rw-r-----@ 1 clburlison  admin    10M Apr 17 13:20 ADPassMon-2.0.9-web.dmg
-rw-r--r--@ 1 clburlison  admin   395K Apr 17 13:18 ADPassMon-2.0.9.dmg
```

**Comment by macmule** [comment]
Thanks Clayton. 

It's just a DMG created in diskutil & dragged in, next release it'll be a zipped file uploaded to GitHub pre-release section. 

Regards,

Ben.

**Comment by clburlison** [comment]
:+1:
