### ISSUE TITLE
Login with no password expiration time

### ISSUE THREAD

**Issue by jcosper** [macmule/ADPassMon#91]

**Comment by jcosper** [comment]
It displays 10523287d remaining for an account that does not have a password expiration time.

**Comment by macmule** [comment]
@jcosper please test: https://github.com/macmule/ADPassMon/releases/tag/163

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
