### ISSUE TITLE
plist Preferences Settings For All Users

### ISSUE THREAD

**Issue by nulleddeviant** [macmule/ADPassMon#92]
Hi,

I seem to be having an issue applying preferences to all users on the computer (including any new AD accounts logging in and myself). So, I can go onto the GUI preferences and change that manually just fine but of course it only applies to that account. So, I've followed the Wiki's instructions on copying over the plist to /Library/Preferences so it applies to all users but it doesn't seem to do anything? I've done the chown and chmod commands but still doesn't seem to work?

Is there anything I seem to be doing wrong? I've attached the plist (as DOCX format since Github accepts only that) I have in the system's library/preferences folder currently:

[plist_settings.docx](https://github.com/macmule/ADPassMon/files/652194/plist_settings.docx)

**Comment by jardhug** [comment]
How are you editing the plist? using Text Editor? if you're using Text Editor make sure you're editing in plain text and have smart quotes and dashes off.

This is mine below

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>accTest</key>
	<string>0</string>
	<key>enableNotifications</key>
	<true/>
	<key>isBehaviour2Enabled</key>
	<integer>1</integer>
	<key>prefsLocked</key>
	<string>true</string>
	<key>pwPolicy</key>
	<string>Your new password must be a minimum of 8 characters long, contain a mixture of numbers, uppercase and lowercase letters. It also must not contain any part of your First or Last name or be similar to a previous password.</string>
	<key>selectedBehaviour</key>
	<integer>2</integer>
	<key>selectedMethod</key>
	<integer>0</integer>
	<key>warningDays</key>
	<integer>5</integer>
</dict>
</plist>
```

You can post your code by putting ``` at the front

https://guides.github.com/features/mastering-markdown/

**Comment by nulleddeviant** [comment]
@danprk I'm using TextWrangler so not sure if that's what's causing the problem? I'll try out yours to see if maybe it's something I've written.

EDIT: That doesn't work either -- is it possible there is another plist location I'm not aware about that's overriding this one?

**Comment by jardhug** [comment]
@nulleddeviant are you using an MDM? Casper, Munki?

preferences will either be in 
~/Library/Preferences/
or
/Library/Preferences/
or
/Library/Managed Preferences/

**Comment by nulleddeviant** [comment]
@danprk I'm actually testing this locally before deploying this (which will be in a image). ~/Library/Preferences has my current preferences but of course it's dynamic depending on the user. Not sure how to have the preferences settings applied to all users on the computer instead of putting it in each user's folder manually.

EDIT: Actually, it seems if I try to change the warningdays field in ~/Library/Preferences/org.pmbuko.ADPassMon.plist and save it, it doesn't seem to apply the changes even if I exit ADPassMon and re-open it. It then reverts that field to what was previously set in the GUI. But, if I add the prefslocked field and change it to true or false, it applies the changes when I restart ADPassMon. Weird, huh..

**Comment by jardhug** [comment]
@nulleddeviant Try doing your changes in the GUI, then take the plist from ~/Library/Preferences/ and move it to /Library/Preferences/ (that's the location for all users)

maybe give a restart a go as well.

**Comment by nulleddeviant** [comment]
@danprk Still nothing, not sure what's wrong since I'm doing it from an administrator account. I'll let you know if I figure it out!

**Comment by nulleddeviant** [comment]
Hi @danprk and anybody else who is having the same problem -- it seems that if you chown and chmod the files even when you su root in terminal it doesn't seem to apply the permissions. You have to manually login to the root account on the system and edit the changes from there. Then of course as mentioned above restart the computer when you apply changes to the /Library/Preferences .plist. 

Hope this helps!
