### ISSUE TITLE
Change Password - Not Working?

### ISSUE THREAD

**Issue by nulleddeviant** [macmule/ADPassMon#93]
Hi,

When I try to change the password from ADPassMon I get the "Password change failed. Please Try again." popup. I've checked the closed issues and it seems a few people had problems with it. My account options: "User cannot change password" and "Password never expires" have always been unchecked so not sure if it's an issue with ADPassMon. I'm able to change the password through the OS X login popup just fine and the keychain gets synced right away with the new password. 

Am I missing something? 

Thanks!

**Comment by macmule** [comment]
@nulleddeviant can you try a pre-release & then post the log found in ~/Library/Logs/ADPassmon.log?

https://github.com/macmule/ADPassMon/releases/tag/163

**Comment by nulleddeviant** [comment]
@macmule, I tried the pre-release but didn't seem to work. I'll put the log below.

> Fri Dec 16 09:08:50 EST 2016 Launching.....
Fri Dec 16 09:08:50 EST 2016 ADPassMon Version: 2.21.0 (163)
Fri Dec 16 09:08:50 EST 2016 Running on OS 10.11.x
Fri Dec 16 09:08:50 EST 2016 Username: **firstname.lastname**
Fri Dec 16 09:08:50 EST 2016 Set number formatter
Fri Dec 16 09:08:50 EST 2016 Registering defaults..
Fri Dec 16 09:08:50 EST 2016 Retrieving defaults..
Fri Dec 16 09:08:50 EST 2016 Running under a network account.
Fri Dec 16 09:08:50 EST 2016 ADPassMon password method selected
Fri Dec 16 09:08:50 EST 2016 Testing if password can expire…
Fri Dec 16 09:08:50 EST 2016 Password does expire.
Fri Dec 16 09:08:50 EST 2016 Starting manual process…
Fri Dec 16 09:08:50 EST 2016 Domain test succeeded.
Fri Dec 16 09:08:51 EST 2016 Domain test succeeded.
Fri Dec 16 09:08:51 EST 2016 myDomain: **REMOVED**
Fri Dec 16 09:08:51 EST 2016 myLDAP: **REMOVED**
Fri Dec 16 09:08:51 EST 2016 Got expireDateUnix from msDS: 1482681210
Fri Dec 16 09:08:51 EST 2016 Using alt method
Fri Dec 16 09:08:51 EST 2016 mySearchBase: **REMOVED**
Fri Dec 16 09:08:51 EST 2016 pwdSetDateUnix via DSCL: 131193788109604848
Fri Dec 16 09:08:51 EST 2016 pwdSetDate epoch: 1474905000
Fri Dec 16 09:08:51 EST 2016 Today epoch: 1481897331
Fri Dec 16 09:08:51 EST 2016 Days Since Set: 80.929756944444
Fri Dec 16 09:08:51 EST 2016 alt daysUntilExp: 9.070243055556
Fri Dec 16 09:08:51 EST 2016 alt daysUntilExpNice: 9
Fri Dec 16 09:08:51 EST 2016 alt secondsTilExpiry: 783669
Fri Dec 16 09:08:51 EST 2016 Got expireDateUnix from alt: 1482681000
Fri Dec 16 09:08:51 EST 2016 expirationDate: Sun Dec 25 10:50:00 EST 2016
Fri Dec 16 09:08:51 EST 2016 Triggering notification…
Fri Dec 16 09:08:51 EST 2016 ADPassMon password method selected
Fri Dec 16 09:08:51 EST 2016 Testing Keychain Lock state...
Fri Dec 16 09:08:51 EST 2016 Keychain unlocked...
Fri Dec 16 09:09:14 EST 2016 Password change failed.
Fri Dec 16 09:09:30 EST 2016 Password change failed.
Fri Dec 16 09:09:50 EST 2016 Password change failed.
 
Removed domain name for security purposes (since this is public) but everything else should be there. Hopefully this helps you find the problem!

**Comment by macmule** [comment]
@nulleddeviant that is helpful :)

So seems we're ending up at: https://github.com/macmule/ADPassMon/blob/master/ADPassMon/ADPassMonAppDelegate.applescript#L1085

Can you try the following in Terminal, changing oldPassword & newPassword as applicable.. then paste the output?

`dscl . -passwd /Users/$USER oldPassword newPassword`

**Comment by nulleddeviant** [comment]
@macmule Just tried it, here's the output:

> COMPUTER NAME:~ root# dscl . -passwd /Users/firstname.lastname/ $oldPass $newPass
passwd: Invalid Path
<dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)
COMPUTER NAME:~ root# dscl . -passwd /Users/test.account/ $oldPass $newPass
passwd: Invalid Path
<dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)

Tried it with two separate accounts just in case.

**Comment by macmule** [comment]
hmm.. did you add the / after the username? can you try without that?

**Comment by nulleddeviant** [comment]
@macmule I'm used to pressing tab to finish a command so I did by accident! I tried without it and still same error. :(

**Comment by macmule** [comment]
Can you try: `dscl . -read /Users/$USER`? Does that error?

**Comment by nulleddeviant** [comment]
Yes it does, sadly!

> COMPUTER NAME:~ root# dscl . -read /Users/test.account
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)

The directory does exist, so not sure why it's giving out that error.

**Comment by macmule** [comment]
@nulleddeviant what's the path to the users home folder?

**Comment by nulleddeviant** [comment]
The path is: /Users/test.account

I got that path straight from Finder.

When you mentioned that, I actually tried going on the actual account to see if it produces a different error, but no avail, same errors.

**Comment by nulleddeviant** [comment]
**Update**

So, I've been looking around to see why DSCL isn't working so I tried _dscl . -ls /Users_ and the accounts I'm trying aren't showing up, only local accounts are showing up. Not sure if this is of any help!

**Comment by nulleddeviant** [comment]
**Update**

So, I was able to find the AD directory dscl utilizes. I'm able to read the account successfully but changing the password gives me an error.

Here's the read action that might help --

`$COMPUTER:/ admin$ dscl /Active\ Directory/$Domain/All\ Domains -read /Users/test.account`

```
dsAttrTypeNative:accountExpires:
 9223372036854775807
dsAttrTypeNative:badPasswordTime: 131262966630776358
dsAttrTypeNative:badPwdCount: 0
dsAttrTypeNative:cn:
 Test Account
dsAttrTypeNative:codePage: 0
dsAttrTypeNative:countryCode: 0
dsAttrTypeNative:distinguishedName:
 CN=Test Account,OU=Users,OU=IT,OU=$Parent,DC=corp,DC=$Domain,DC=net
dsAttrTypeNative:dSCorePropagationData: 20161215165751.0Z 20161209161535.0Z 16010101000000.0Z
dsAttrTypeNative:instanceType: 4
dsAttrTypeNative:lastLogoff: 0
dsAttrTypeNative:lastLogon: 131269803117272224
dsAttrTypeNative:lastLogonTimestamp: 131269778275253339
dsAttrTypeNative:logonCount: 230
dsAttrTypeNative:msDS-SupportedEncryptionTypes: 0
dsAttrTypeNative:name:
 Test Account
dsAttrTypeNative:objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=corp,DC=$Domain,DC=net
dsAttrTypeNative:objectClass: top person organizationalPerson user
dsAttrTypeNative:objectGUID:
 f326eaee b271c34d 915a909a 587a8d68
dsAttrTypeNative:objectSid:
 01050000 00000005 15000000 8ed18b2c 343998e7 05495acf b1090000
dsAttrTypeNative:sAMAccountName: test.account
dsAttrTypeNative:sAMAccountType: 805306368
dsAttrTypeNative:userAccountControl: 512
dsAttrTypeNative:userPrincipalName: test.account@corp.$Domain.net
dsAttrTypeNative:uSNChanged: 7325443
dsAttrTypeNative:uSNCreated: 7147027
dsAttrTypeNative:whenChanged: 20161223144347.0Z
dsAttrTypeNative:whenCreated: 20161209161534.0Z
AltSecurityIdentities: Kerberos:test.account@corp.$Domain.net
AppleMetaNodeLocation:
 /Active Directory/$Domain/corp.$Domain.net
AppleMetaRecordName:
 CN=Test Account,OU=Users,OU=IT,OU=$Parent,DC=corp,DC=$Domain,DC=net
AuthenticationAuthority: ;Kerberosv5;;test.account@$Domain;$Domain; ;NetLogon;test.account;$Domain
Comment:
 Account for testing purposes.
EMailAddress: test.account@madeupemail.com
FirstName: Test
GeneratedUID: EEEA26F3-71B2-4DC3-915A-909A587A8D68
LastName: Account
MCXFlags:
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>has_mcx_settings</key>
	<true/>
</dict>
</plist>`

MCXSettings:
 <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>mcx_application_data</key>
	<dict>
		<key>com.apple.MCX</key>
		<dict>
			<key>Forced</key>
			<array>
				<dict>
					<key>mcx_precedence</key>
					<integer>500</integer>
					<key>mcx_preference_settings</key>
					<dict>
						<key>com.apple.cachedaccounts.CreateAtLogin</key>
						<false/>
						<key>com.apple.cachedaccounts.WarnOnCreate</key>
						<true/>
					</dict>
				</dict>
			</array>
		</dict>
		<key>com.apple.dock</key>
		<dict>
			<key>Forced</key>
			<array>
				<dict>
					<key>mcx_precedence</key>
					<integer>500</integer>
					<key>mcx_preference_settings</key>
					<dict>
						<key>AppItems-Raw</key>
						<array/>
						<key>DocItems-Raw</key>
						<array/>
						<key>MCXDockSpecialFolders-Raw</key>
						<array>
							<string>AddDockMCXOriginalNetworkHomeFolder</string>
						</array>
					</dict>
					<key>mcx_union_policy_keys</key>
					<array>
						<dict>
							<key>mcx_input_key_names</key>
							<array>
								<string>AppItems-Raw</string>
							</array>
							<key>mcx_output_key_name</key>
							<string>static-apps</string>
							<key>mcx_remove_duplicates</key>
							<true/>
						</dict>
						<dict>
							<key>mcx_input_key_names</key>
							<array>
								<string>DocItems-Raw</string>
							</array>
							<key>mcx_output_key_name</key>
							<string>static-others</string>
							<key>mcx_remove_duplicates</key>
							<true/>
						</dict>
						<dict>
							<key>mcx_input_key_names</key>
							<array>
								<string>MCXDockSpecialFolders-Raw</string>
							</array>
							<key>mcx_output_key_name</key>
							<string>MCXDockSpecialFolders</string>
							<key>mcx_remove_duplicates</key>
							<true/>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>loginwindow</key>
		<dict>
			<key>Forced</key>
			<array>
				<dict>
					<key>mcx_precedence</key>
					<integer>500</integer>
					<key>mcx_preference_settings</key>
					<dict>
						<key>AutoLaunchedApplicationDictionary-raw</key>
						<array>
							<dict>
								<key>AuthenticateAsLoginUserShortName</key>
								<true/>
								<key>MCX-NetworkHomeDirectoryItem</key>
								<true/>
							</dict>
						</array>
					</dict>
					<key>mcx_union_policy_keys</key>
					<array>
						<dict>
							<key>mcx_input_key_names</key>
							<array>
								<string>AutoLaunchedApplicationDictionary-raw</string>
							</array>
							<key>mcx_output_key_name</key>
							<string>AutoLaunchedApplicationDictionary-managed</string>
							<key>mcx_remove_duplicates</key>
							<true/>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>

NFSHomeDirectory: /Users/test.account
Password: ********
PrimaryGroupID: 345362195
PrimaryNTDomain: $Domain
RealName:
 Test Account
RecordName: test.account
RecordType: dsRecTypeStandard:Users
SMBGroupRID: 513
SMBPasswordLastSet: 131262990301912200
SMBPrimaryGroupSID: S-1-5-21-747360654-3885513012-3478800645-513
SMBSID: S-1-5-21-747360654-3885513012-3478800645-2481
UniqueID: 1860839155
UserShell: /bin/bash
```

Now, here's where I try to change the password: 
> $COMPUTER:/ admin$ dscl /Active\ Directory/$DomainName/All\ Domains -passwd /Users/test.account $TempPass $TempPass2
> passwd: DS error: eDSAuthPasswordQualityCheckFailed
> <dscl_cmd> DS Error: -14165 (eDSAuthPasswordQualityCheckFailed)

The password age is more than 1 day old, the password complexity requirements are being fulfilled, and that is the right AD directory, so just stuck on this one little problem. Still researching to see if the error is common.

**Comment by nulleddeviant** [comment]
Solved -- had to re-do the group policy and push it out again. The change password now works! Make sure the security settings are being fulfilled and that group policy is working on both Windows & OS X.
