### ISSUE TITLE
Help with installation - Please forgive me

### ISSUE THREAD

**Issue by thesling1** [macmule/ADPassMon#94]
Hello!

For the life of me I do not understand how to install this tool...  The product looks awesome and looks to be exactly what I need... But I just don't get it.

Would someone be able to create a youtube video, or full step by step print screens of the process.  I imagine it is entirely likely it is easier than it looks but... Sorry launch agent?  Plist?

I place the adpass mon program in the applications directory and a plist file int he library folder?  And then there is an install recipe too?  What is this?

Finally, is there somewhere to make a donation?

Thank you,
Tony H.

**Comment by macmule** [comment]
Hi @thesling1,

Can you please join the [MacAdmins slack](https://macadmins.herokuapp.com).

There's a number of great channels there where folks can help (myself included).
