### ISSUE TITLE
Notification every 10 minutes after the 14 days expiration date

### ISSUE THREAD

**Issue by simonelberts** [macmule/ADPassMon#95]
Is there a way to customize the Notification center alerts? Our users are receiving them every 10 min after there password is after the 14 days expiration day. I know this should be default be like 12 hours, but that's not the case in our situation.
![014392c3f1f9466fa725477caad4a50a_720](https://cloud.githubusercontent.com/assets/9071654/22648721/2fb77d44-ec78-11e6-91c2-7ce1d8192e45.png)
[ADPassMonLog.txt](https://github.com/macmule/ADPassMon/files/754689/ADPassMonLog.txt)

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
