### ISSUE TITLE
Feature Request - Check alternate account

### ISSUE THREAD

**Issue by kn1ght0wl** [macmule/ADPassMon#96]
I have two AD accounts, my primary account which I use to login daily and a privileged account that I use for admin tasks.  Would it be possible to use this tool to check the password expiration of that priv. account when logged in using my normal account?  I get warnings 15 days out for my normal account, however, the privileged account is not used to directly login to a server/workstation, so, no warnings...

**Comment by macmule** [comment]
@kn1ght0wl Sadly no.

http://nomad.menu allows you to switch user accounts however, might be worth trying that.
