### ISSUE TITLE
Updating all Keychains using the same password

### ISSUE THREAD

**Issue by captaincoconuts** [macmule/ADPassMon#97]
Is it possible for ADPassMon to update any other Keychains using the same password, we have printers and Outlook accounts with the Keychain password changed. It would be great if those could be updated as seamlessly as the main password.

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
